### ISSUE TITLE
[Other issue]: Robot state isn't shown on dashbord (web)

### ISSUE THREAD

**Issue by batechgroup35** [open-rmf/rmf-web#1010]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

version used : 
ROS : Jazzy (July 2024)

I installed the last available version of open-rmf and ros jazzy and i wanted to start some rmf-demo to test the features.

The robot state on web browser doesn't appear (see below):

![Screenshot from 2024-09-17 11-49-35](https://github.com/user-attachments/assets/05b1c6db-b938-4048-b86d-52f2885d5d6c)

someone have any idea to how fix this issue ?

[ros2_launch_rmf_demos_gz_office.txt](https://github.com/user-attachments/files/17026508/ros2_launch_rmf_demos_gz_office.txt)

**Comment by aaronchongth** [comment]
https://github.com/open-rmf/rmf_demos?tab=readme-ov-file#rmf-web-quick-start

Looks like you missed out the instructions to launch with the `server_uri:=ws://localhost:8000/_internal` launch parameter
