### ISSUE TITLE
[Bug]: Dashboard occasionally does not load. Favorite Tasks broken

### ISSUE THREAD

**Issue by MrOCW** [open-rmf/rmf-web#1012]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### OS and version

Ubuntu 24

### Open-RMF installation type

Source build

### Open-RMF version or commit hash

1ab38d717283aece61050874b9827d111de66b29 rmf_ros2

### ROS distribution

Rolling

### ROS installation type

Binaries

### Description of the bug

Using the dashboard docker image to run. Sometimes the dashboard does not load at all. When it does, favorite tasks' Submit button is greyed out. Manually sending tasks works. The dashboard was stable with commit `89c9d7222811da5cd8711f6f8f02c050e29f72e1`

### Steps to reproduce the bug

Run dashboard with provided docker image

### Actual behavior

Stable dashboard

**Comment by aaronchongth** [comment]
Hello @MrOCW! Before we dive into the issue, could you
* Describe your setup, is the API server running on the same machine? Are you trying to access the dashboard from the same machine?
* Can you describe what "does not load" mean? Is it a 404? Does it load forever? Can you provide logs from the browser?

For the favorite task submit button, it will only be disabled if the task type is `Custom Compose`. Can I confirm that is what you're trying to do?

Unless you are saying after selecting a previously saved favorite task (save a patrol task as favorite, and click on the saved task on the left, which fills out the form), and the submit button is greyed out.
* What task is it?
* Was there a field that is not filled out? The submit button is greyed out when the form is not fully filled out
* As for manually sending the same task works, after selecting the favorite task, can you change some of the form values a little to see if it triggers the submit button to be usable again? This is to check if there is a bug where the favorite task is not triggering the right checks for the submit button

**Comment by MrOCW** [comment]
Hi @aaronchongth, 

> is the API server running on the same machine
yes. api server and dashboard is running on docker

> what "does not load" mean
the screen is just white forever

> it will only be disabled if the task type is Custom Compose 
it is a Patrol task

![image](https://github.com/user-attachments/assets/bb18cac7-5bd7-48f1-82af-4aeb96f70d32)
After clicking favourite task, the form becomes like this but the button is still greyed out.

**Comment by aaronchongth** [comment]
> the screen is just white forever

Can you provide browser logs when this happens?

> After clicking favourite task, the form becomes like this but the button is still greyed out. I have reverted to before the commit and it is fixed

The culprit is most likely https://github.com/open-rmf/rmf-web/pull/1004/files#diff-678b11fe9f77dceefe5d736a3944e36645c4702dd56ffd499318526da6cf20ceL127, can you set up the dashboard from source and try reverting this line to see if that is the fix?

**Comment by MrOCW** [comment]
> Can you provide browser logs when this happens?

```
[Warning] [blocked] The page at https://<my domain>/robots was not allowed to run insecure content from ws://localhost:8006/. (index-CCapogoY.js, line 368)

[Warning] [blocked] The page at https://<my domain>/robots was not allowed to display insecure content from http://localhost:8000/user. (index-CCapogoY.js, line 292)

[Error] Not allowed to request resource
	(anonymous function) (index-CCapogoY.js:292:7453)
	Promise
	(anonymous function) (index-CCapogoY.js:292:5500)
	dI (index-CCapogoY.js:294:513)
[Error] XMLHttpRequest cannot load http://localhost:8000/user due to access control checks.
	(anonymous function) (index-CCapogoY.js:292:7453)
	Promise
	(anonymous function) (index-CCapogoY.js:292:5500)
	dI (index-CCapogoY.js:294:513)
[Error] Axios response error: AxiosError: Network Error
	(anonymous function) (index-CCapogoY.js:368:6429)
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'a.response.status')
	(anonymous function) (index-CCapogoY.js:372:23510)
```

**Comment by aaronchongth** [comment]
May I check what browser are you running the dashboard on?

**Comment by aaronchongth** [comment]
As for the intermittent connection, my hunch is that it is something related to your browser or setup,
A quick search pointed me to https://discussions.apple.com/thread/254087609?sortBy=rank
so far I have not been able to reproduce it

while the favorite task issue has been resolved with https://github.com/open-rmf/rmf-web/pull/1013.
