### ISSUE TITLE
`node-canvas` does not have prebuilt binaries for node 22

### ISSUE THREAD

**Issue by koonpeng** [open-rmf/rmf-web#1023]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### OS and version

Ubuntu 24.04

### Open-RMF installation type

Source build

### Open-RMF version or commit hash

main

### ROS distribution

Jazzy

### ROS installation type

Binaries

### Description of the bug

The version of `node-canvas` (v2) used does not have prebuilt binaries for the latest node lts (node 22). It can still be built from source but you will need to install several system dependencies. We should update to `node-canvas` >= 3 which uses the newer NAPI api.

### Steps to reproduce the bug

`pnpm install` on node 22.

**Comment by koonpeng** [comment]
This is causing nightly to fail.

**Comment by zzttqu** [comment]
I have the same problem when I install the dependencies on ros2-jazzy. After I remove the canvas from package.json, it seems work well.
