### ISSUE TITLE
[Other issue]: Unable to start the rmf-web 

### ISSUE THREAD

**Issue by pvg6** [open-rmf/rmf-web#1025]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

I am using the humble distro...
I builded the rmf_demos packages and simulation things are working...

When i am run the rmf web i am facing this issue..

![Screenshot from 2024-11-11 11-27-36](https://github.com/user-attachments/assets/28191b27-d58f-4f1a-abdb-8e4a812f3c0b)

**Comment by aaronchongth** [comment]
Hi @pvg6! Can I confirm that the issue is due to not sourcing the RMF workspace?
Describing the solution before closing a ticket can help other folks if they search for issue keywords

**Comment by pvg6** [comment]
@aaronchongth ...

How I resolved the above issue... I clone the rmf_internal_msgs, build and source it...
It helped me to solve the issue..

**Comment by pvg6** [comment]
@aaronchongth ..

Can you please guide me how to create custom tasks?..

**Comment by aaronchongth** [comment]
Gotcha, thanks.
As mentioned in https://github.com/open-rmf/free_fleet/issues/158, please describe in detail what you're trying to achieve in a discussion. A quick search showed that we have an ongoing discussion https://github.com/open-rmf/rmf/discussions/155 regarding this topic. Please furnish your question with more information, and links to code if possible so we can understand the issue better

**Comment by pvg6** [comment]
@aaronchongth 
.

I want to achieve object detection by robot. When we send the robot to particular place. When it reach the destination then custom task should do detection of that place.. After finishing the custom task it will continue to RMF task..


I am Using rmf_demos_fleet_adapter and using turtlebot3..
I did RMF on my single real turtlebot3 without zenoh bridge. We compulsory need zenoh bridge? Because some time I am getting Extraplotation error...[](https://github.com/open-rmf/free_fleet/issues/156)


Please help me

**Comment by aaronchongth** [comment]
@pvg6, as mentioned, this is out of the scope of https://github.com/open-rmf/rmf-web, please repost this as a discussion ticket on https://github.com/open-rmf/rmf/discussions/155, I will follow up there accordingly

**Comment by pvg6** [comment]
@aaronchongth yeah I posted and can you confirm about the above zenoh bridge and extraplotation error [link](https://github.com/open-rmf/free_fleet/issues/156)
