### ISSUE TITLE
[Other issue]: ImportError: cannot import name 'Alert' from 'rmf_task_msgs.msg'

### ISSUE THREAD

**Issue by cardboardcode** [open-rmf/rmf-web#1029]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

Creating a seperate issue thread to capture details and solution of the following error when first building `rmf-web` `0.1.0` or `0.1.0` that relies on ROS 2 Jazzy:

> ImportError: cannot import name 'Alert' from 'rmf_task_msgs.msg'

Similar to #1025. However, the thread seems to have digressed to a different topic about Zenoh. Therefore, created this thread to focus on the core issue highlighted.

## **Steps To Reproduce** :books: 
```bash
cd $HOME
```

```bash
git clone https://github.com/open-rmf/rmf-web.git --branch 0.2.0 --depth 1 --single-branch
```

```bash
cd rmf-web
```

2. Create the following `Dockerfile`:

```bash
#-----------------------
# Stage 1 - Dependencies
#-----------------------
FROM ros:jazzy-ros-core
RUN apt-get update

RUN apt-get install -y \
    git \
    curl \
    build-essential \
    python3-pip \
    python3-venv \
    python3-rosdep \
    python3-colcon-common-extensions \
    ros-$ROS_DISTRO-rmf-*

ENV PIP_BREAK_SYSTEM_PACKAGES=1

WORKDIR /
COPY ./ ./rmf-web

RUN curl -fsSL https://get.pnpm.io/install.sh | bash -
ENV PNPM_HOME /root/.local/share/pnpm
ENV PATH "$PNPM_HOME:$PATH"
RUN pnpm env use --global 20
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get update && apt-get install -y \
    nodejs \
    jq && \
  pip3 install pipenv \
  && rm -rf /var/lib/apt/lists/*

#-----------------
# Stage 2 - build
#-----------------

WORKDIR /rmf-web/
RUN pnpm config set unsafe-perm
RUN pnpm install
RUN pnpm store prune
WORKDIR /rmf-web/packages/dashboard

#----------
# Stage 3 - cleanup
#----------

ENTRYPOINT ["/ros_entrypoint.sh"]
# CMD ["pnpm", "start"]
```

3. Build the docker image:
```bash
docker build -t rmf_web_custom:jazzy .
```

4. Run the docker image as container: 
```bash
docker run -it --rm \
  --name rmf_web_custom_c \
  --network host \
  -v /dev/shm:/dev/shm \
rmf_web_custom:jazzy bash
```

## **Expected Behaviour** :green_circle: 
rmf-web compiles with VITE without error.

## **Actual Behaviour** :red_circle: 
rmf-web fails to compile with VITE with the error highlighted at the start of this thread.

**Comment by cardboardcode** [comment]
## Cause of Issue :bug: 

The source of the error is due to `Alert.msg` not being available yet in the ROS 2 RMF Jazzy and Humble binaries.

`Alert.msg` is only available on the GitHub repository for `rmf_internal_msgs` as referenced in [this link](https://github.com/open-rmf/rmf_internal_msgs/blob/main/rmf_task_msgs/msg/Alert.msg).

## Temporary Workaround :adhesive_bandage: 
As suggested in the issue referenced before, the current workaround would be to build and source your own `rmf_internal_msgs` which one can do so by following the instructions below:

```bash
cd $HOME
```

```bash
mkdir -p rmf_ws/src && cd rmf_ws/src
```

```bash
git clone https://github.com/open-rmf/rmf_internal_msgs.git --branch main
```

```bash
cd rmf_internal_msgs && git checkout 9ff25f4
```

```bash
cd $HOME/rmf_ws
```
```bash
source /opt/ros/$ROS_DISTRO/setup.bash
```

```bash
colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
```

```bash
source $HOME/devel/setup.bash
```

Then proceed to run `pnpm start` for `rmf-web`.

## Remarks :speech_balloon: 
As a proper long term solution, would suggest having `Alert.msg` included in ROS 2 Jazzy and Humble binaries.

**Comment by aaronchongth** [comment]
@cardboardcode thanks for the heads up! You're right we didn't manage to backport the messages into `jazzy` and have started the process of doing so, https://github.com/open-rmf/rmf_internal_msgs/pull/75, the release process will take a while. Once the binaries have been updated I'll close this ticket.

**Comment by aaronchongth** [comment]
@cardboardcode Apologies, I will need to update my comment on this topic, as mentioned during our PMC meeting and review of our release policy, we will not be backporting any new features onto distro releases, this unfortunately includes the alert related messages that this PR is about.

These messages are released as part of `rolling` but not other distros at the moment. We will suggest that users build minimal workspaces with the latest `rmf_internal_msgs` as mentioned in the comment above. Depending on the fleet adapter's implementation, it might require these new messages too, to fully utilize the feature.

We will look into how we can improve our documentation regarding this particular dilemma. Thanks!
