### ISSUE TITLE
[Other issue]: I am not able to see the map in rmf web.

### ISSUE THREAD

**Issue by harshp1509** [open-rmf/rmf-web#1033]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

When i am running rmf demos maps than i can see the map but when i am trying with my own created map which is not seen in rmf-web. i can see map in gazebo and rviz. all rmf things are working fine in my own map. only problem i am facing that map in not loading in rmf web

**Comment by harshp1509** [comment]
i got the solution

**Comment by aaronchongth** [comment]
hi @harshp1509 can you perhaps elaborate a little on what your solution was? This may help others when they search through issues with the same problem.

**Comment by yutaroha** [comment]
Hello there,
I am using RMF conveniently. I have experienced a similar phenomenon. In my case, it did not work when no walls were set, but it started to work when I added a wall.

**Comment by harshp1509** [comment]
i did the same thing😁
