### ISSUE TITLE
[Bug]: Missing Alert/AlertResponse Messages Cause API Server Failure in RMF Web with ROS2 Jazzy

### ISSUE THREAD

**Issue by saujanya01** [open-rmf/rmf-web#1041]
### Before proceeding, is there an existing issue or discussion for this?

- [x] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### OS and version

Ubuntu 24.04

### Open-RMF installation type

Binaries

### Open-RMF version or commit hash

release-jazzy-240617

### ROS distribution

Jazzy

### ROS installation type

Binaries

### Package or library, if applicable

rmf_task_msgs

## Description
When using ROS2 Jazzy, there is a dependency mismatch between `rmf-web` and `rmf_internal_msgs`. The API server attempts to import `Alert` and `AlertResponse` message types from `rmf_task_msgs`, but these messages are not available in the Jazzy branch of `rmf_internal_msgs`.

### Current Behavior
- API server fails to run due to missing message types
- Error received: "Alert not found in rmf_task_msgs"

### Environment
- OS - Ubuntu 24.04(arm64 in rpi5)
- python - 3.12
- node - 20
- ROS2 Distribution: Jazzy
- Package: rmf-web (api-server)
- Related Package: rmf_internal_msgs
- Both rmf and ros have been installed using the binary

### Relevant Code References
1. Missing message definitions in rmf_internal_msgs:
   - Branch: jazzy
   - Path: rmf_internal_msgs/rmf_task_msgs/msg
   - Link: https://github.com/open-rmf/rmf_internal_msgs/tree/jazzy/rmf_task_msgs/msg

2. Usage in api-server:
   - File: packages/api-server/api_server/gateway.py
   - Lines: 32-33
   - Link: https://github.com/open-rmf/rmf-web/blob/main/packages/api-server/api_server/gateway.py#L32-L33

### Questions
1. Which branch of rmf-web is compatible with ROS2 Jazzy?
2. If there is no compatible branch, what is the recommended approach for using rmf-web with ROS2 Jazzy?

### Steps to reproduce the bug

1. install ros2 jazzy (https://docs.ros.org/en/rolling/Installation/Ubuntu-Install-Debs.html)
2. install rmf (https://docs.ros.org/en/rolling/Installation/Ubuntu-Install-Debs.html)
3. clone and pnpm install packages of rmf-web (https://github.com/open-rmf/rmf-web)
4. run rmf-web's api-server (a. `cd packages/api-server`, b. `pnpm start`)

**Comment by aaronchongth** [comment]
Hey @saujanya01! Sorry to hear that you have this issue too. Check out the previous similar ticket, https://github.com/open-rmf/rmf-web/issues/1029, where we discussed why we will not be including the alert messages into the Jazzy release. TLDR, we only allow backporting bug fixes into releases, and not new features, therefore the alert messages will need to stay on `main` until a new release starts.

I'd suggest building `rmf_internal_msgs` from source in a new minimal workspace, source it and run the API server from there. 

Will be closing this ticket now.

**Comment by saujanya01** [comment]
Thanks for clarification @aaronchongth. So, just for more clarity, will the rmf alert messages be included in binary for the next ros release(i.e. rolling) or next rmf release of jazzy?

**Comment by aaronchongth** [comment]
It will only be included in the next ROS 2 release, https://docs.ros.org/en/rolling/Releases/Release-Kilted-Kaiju.html

**Comment by aaronchongth** [comment]
Can you verify what the branch of `rmf_internal_msgs` repository is that you have built, and that it contains the `Alert` related messages shown here, https://github.com/open-rmf/rmf_internal_msgs/tree/main/rmf_task_msgs/msg

**Comment by aaronchongth** [comment]
Our most recent Jazzy CI still passed, https://github.com/open-rmf/rmf-web/actions/runs/14026040119/job/39264775691, so it would seem that building, installing and running the API server from a [fresh docker image](https://github.com/open-rmf/rmf-web/blob/main/.github/minimal-rmf/Dockerfile#L2), specifically `ros:jazzy-ros-base` works. I'd advise to review the steps that you have followed, or start from new terminals, or check that your terminal's environment variables are not crossed.

For reference, you can try these steps from a fresh docker image too,

```bash
# pull and enter docker
docker pull ros:jazzy-ros-base
docker run -it ros:jazzy-ros-base bash

# within docker, set up workspace
mkdir -p /home/ws/src
cd /home/ws/src
git clone https://github.com/open-rmf/rmf_internal_msgs
git clone https://github.com/open-rmf/rmf_building_map_msgs
cd /home/ws/
source /opt/ros/jazzy/setup.bash
colcon build

# set up rmf-web
apt update && apt install curl python3-venv ros-jazzy-rmw-cyclonedds-cpp -y
curl -fsSL https://get.pnpm.io/install.sh | bash -
source /root/.bashrc
pnpm env use --global lts
cd /home
git clone https://github.com/open-rmf/rmf-web
cd rmf-web
pnpm install --filter api-server...
cd packages/api-server

# source built workspace and run api-server
source /home/ws/install/setup.bash
export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
pnpm start
```

In the future, using docker images or checking the our CI is a good way to debug if there is something amiss with your setup

**Comment by aaronchongth** [comment]
As mentioned in this ticket and https://github.com/open-rmf/rmf-web/issues/1029#issuecomment-2485155781, the `Alert` related messages that is required by the API server on `main` will not be backported back to `jazzy` and is only available from the `main` branches of `rmf_internal_msgs`.

The `jazzy-release` and `jazzy` branches will not contain these messages, you can check them out.

So `main` is what you should use. These new messages do not interfere with past features, so if you'd like to cut down on build-time, you can also opt to use binaries for all the RMF packages, except for the packages in repositories `rmf_internal_msgs` and `rmf_demos`
