### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by matiasbavera** [open-rmf/rmf-web#132]
Since users will be staring at the screen the whole day I think a dark mode will be appreciated. E.g: https://docs.docker.com/

![image](https://user-images.githubusercontent.com/11761240/95379905-5ea9eb00-08bc-11eb-93fd-b95d81ceb826.png)

**Comment by koonpeng** [comment]
The main challenge of this is that the map image is usually white-ish. We could try inverting the colors.

**Comment by matiasbavera** [comment]
related to #272 closing this one
