### ISSUE TITLE
Smooth robot animations

### ISSUE THREAD

**Issue by koonpeng** [open-rmf/rmf-web#167]
The robot icon is updated only when a new state is received, this is at 10hz from the gazebo fleet adapter. This is fine for showing the robot's location but results in movements looking laggy.

A proposal is to hold back the state update 1 message (or "frame") and perform smooth animations by interpolating the frames. Downside of course is that updates are slightly delayed but afaik the dashboard is never intended to be a high precision display of rmf.

**Comment by aaronchongth** [comment]
Closing as this is no longer a priority for the dashboard for now. Will re-open if we have incoming requirements for smoother, realistic visualizations.
