### ISSUE TITLE
Check if we can replace smoke test with screenshot snapshot diffing

### ISSUE THREAD

**Issue by matiasbavera** [open-rmf/rmf-web#243]
Now that we use karma on the react-component package, It'll be good to check if we can replace smoke tests with screenshot snapshot diffing

**Comment by koonpeng** [comment]
I looked into this abit, it doesnt seem possible (at least not easy) because karma doesnt expose chrome devtools.

**Comment by matiasbavera** [comment]
Yeah, I dug into this too and you're right, although some guys use puppeteer to make a screenshot, they kind of get the running instance of puppeteer and extend the functionalities of the instance (add screenshots, compare screenshots, etc) 

You can check that here: https://github.com/rsamec/karma-puppeteer-launcher

I played with it but without success.

**Comment by matiasbavera** [comment]
Should we keep the "smoke tests" or should we tackle that in a different way?. Should we use something like selenium to do it? 

Also I found a interesting tool to take screenshots to the storybook components https://medium.com/bleeding-edge/screenshot-testing-with-react-and-storybook-19ab7e49ec92

**Comment by koonpeng** [comment]
I think just leave the smoke tests as is for now. Most tools that support taking screenshots are e2e, so they dont work well with coverage collection. But feel free to tackle this challenge if you are up for it.

**Comment by koonpeng** [comment]
Based on the initial research the answer is "no", karma does not expose webdriver functions.
