### ISSUE TITLE
Robot States Report

### ISSUE THREAD

**Issue by matiasbavera** [open-rmf/rmf-web#253]
## Feature request
Robot States Report

### Description
Include a `Robot States` report in the Report section.

### Implementation considerations
The report should include, `the name, robot's mode,  DateTime, location, battery, task (if any), path (if any).` More fields can be added in case of need.

A table to show the information should be created in the UI. An endpoint and the corresponding filter logic should be implemented in the backend.

**Comment by vallq** [comment]
Fixed by #297
