### ISSUE TITLE
Workcell States report 

### ISSUE THREAD

**Issue by matiasbavera** [open-rmf/rmf-web#256]
## Feature request
 Workcell States report 

### Description
Include a Workcell States report in the Report section.

### Implementation considerations
The report should include:
* guid
* workcell's mode
* datetime 
* request_guid_queue, 
* name(?). 

More fields could be added in case of need.

A table should be created in the UI to display the information. 

An Endpoint and its corresponding filter logic should be implemented in the backend.

**Comment by aaronchongth** [comment]
Reporting has been removed via https://github.com/open-rmf/rmf-web/pull/628
