### ISSUE TITLE
Robot Actions report

### ISSUE THREAD

**Issue by matiasbavera** [open-rmf/rmf-web#257]
## Feature request
Robot Actions report 

### Description
Include a Robot Actions report in the Report section.

### Implementation considerations
The report should include:
* robot's name
* datetime
* robot's actions (sounds, bays open/close, etc).

More fields could be added in case of need.

A table should be created in the UI to display the information. 

An Endpoint and its corresponding filter logic should be implemented in the backend.

**Comment by matiasbavera** [comment]
Hi @codebot , please feel free to add more fields that should include the report and more action examples. 

Thanks!

**Comment by aaronchongth** [comment]
Reporting has been removed via https://github.com/open-rmf/rmf-web/pull/628
