### ISSUE TITLE
User Actions report

### ISSUE THREAD

**Issue by matiasbavera** [open-rmf/rmf-web#258]
## Feature request
User Actions report 

### Description
Include a User Actions report in the Report section.

### Implementation considerations
The report should include: 
* username
* user role
* the type of action (if we have one in the future)
* action description
* object involved
* datetime

More fields could be added in case of need.

A table should be created in the UI to display the information. 

An Endpoint and its corresponding filter logic should be implemented in the backend.

**Comment by aaronchongth** [comment]
Reporting has been removed via https://github.com/open-rmf/rmf-web/pull/628
