### ISSUE TITLE
Tasks report

### ISSUE THREAD

**Issue by matiasbavera** [open-rmf/rmf-web#259]
## Feature request
Tasks report 

### Description
Include a Tasks report in the Report section.

### Implementation considerations

The report should include, tasks issued, completed, and failed. As for the report's fields should contain 
* task_id
* state
* status
* submission_time
* start_time
* end_time. 

More fields could be added in case of need.

A table should be created in the UI to display the information. 

An Endpoint and its corresponding filter logic should be implemented in the backend.

**Comment by matiasbavera** [comment]
Hi @koonpeng , should we have this report (with 7 days logs)  on the reporting side, or should this be directly on the dashboard and stored on the rmf-server database?

**Comment by vallq** [comment]
Fixed by #400
