### ISSUE TITLE
Lift States report

### ISSUE THREAD

**Issue by matiasbavera** [open-rmf/rmf-web#260]
## Feature request
Lift States report

### Description
Include a Lift States report in the Report section.

### Implementation considerations

The report should include: 
* lift_time
* lift_name
* available_floors
* current_floor
* destination_floor
* door_state
* motion_state
* available_modes
* current_mode
* session_id
* date_time

More fields could be added in case of need.

A table should be created in the UI to display the information. 

An Endpoint and its corresponding filter logic should be implemented in the backend.

**Comment by vallq** [comment]
Fixed by #297
