### ISSUE TITLE
[throwaway/demo] Modifications to Robots Tab

### ISSUE THREAD

**Issue by Yadunund** [open-rmf/rmf-web#353]
- [x] Fix the sequence of assigned tasks
It seems that the sequence of tasks as displayed in the robot card needs to be reversed. The second screenshot has the correct sequence. Furthermore, there are some extra CHARGEXXXX tasks that are appended that need to be corrected.
![image](https://user-images.githubusercontent.com/13482049/119435862-a13a0e00-bd4d-11eb-81a4-94c0265e3c7e.png)
![image](https://user-images.githubusercontent.com/13482049/119435943-ca5a9e80-bd4d-11eb-989b-ef04e7f130f3.png)

- [x] Update Task Progress
In the screenshot above, the progress dial of the task does not progress

- [x] Update Assigned Tasks
In the screenshot above the Assigned Tasks do not seem to automatically update as tasks are completed

**Comment by koonpeng** [comment]
>  Update Task Progress

>  Update Assigned Tasks

Similar to the auto refresh feature, this is not compatible with the request to use `/get_tasks` exclusively.

**Comment by Yadunund** [comment]
Marking this as resolved 🙏🏼
