### ISSUE TITLE
[throwaway/demo] Modifications to Appearances

### ISSUE THREAD

**Issue by Yadunund** [open-rmf/rmf-web#354]
- [x] ~~Customizable icon for the dashboard instead of the default ROSHealth
It would be great if the user can overwrite a generic icon.png file somewhere that eventually gets rendered at the top left corner. This would make the branding more flexible.~~
![image](https://user-images.githubusercontent.com/13482049/119437071-ee1ee400-bd4f-11eb-91c4-2259e525b00b.png)

- [x] ~~More robot icons
This feature may already exisit but is there a way users can upload custom icons for rendering their robots instead of the circles?~~

**Comment by koonpeng** [comment]
>  More robot icons
Its still using the resources.json workaround in the previous versions of dashboard, you need to add the icons at build time.

**Comment by vallq** [comment]
@matiasbavera yea I think that would be ideal? and yadu has pointed out in the slack thread that this should work!
https://osrf.slack.com/archives/C01ECP3GBTQ/p1621929627099000?thread_ts=1621909289.093400&cid=C01ECP3GBTQ

**Comment by matiasbavera** [comment]
Got it! Let me know if you need help!

**Comment by matiasbavera** [comment]
Hi @Yadunund @tanyouliang95 were you able to set up the new logo and the robot images?

**Comment by Yadunund** [comment]
@matiasbavera yes I was able to setup the new logo. Will close this ticket once https://github.com/open-rmf/rmf_demos/pull/48#issuecomment-851781548 is merged.

**Comment by Yadunund** [comment]
Marking this as resolved. Thanks all!
