### ISSUE TITLE
Storybook freezes when clicking Circular Progress Bar

### ISSUE THREAD

**Issue by vallq** [open-rmf/rmf-web#359]
Storybook freezes when clicking on this component Circular Progress Bar
Related (but not entirely helpful): https://github.com/storybookjs/storybook/issues/1252
This only happened after moving the component into the robot folder and updating the imports.

File in question: `react-components/stories/robots/circular-progress-bar.stories.tsx`

Behaviour:
https://user-images.githubusercontent.com/28668944/119798466-be1d3f80-bf0d-11eb-999b-98f99b938bec.mp4

Does not impact the dashboard, only the react-component package

**Comment by koonpeng** [comment]
fixed by #391
