### ISSUE TITLE
Submitting loop request did not return the correct number of loops

### ISSUE THREAD

**Issue by ChawinTan** [open-rmf/rmf-web#364]
## Bug report

When loop request is submitted with a loop count of  > 1, it will occasionally return a loop count of 1 instead.

### Required information:

- Operating system and version:
  - 
- OpenRMF installation type:
  - 
- OpenRMF version or commit hash
  - 
- ROS distribution and version:
  - 
- ROS installation type:
  - 
- Package or library, if applicable:
  -

**Comment by koonpeng** [comment]
fixed
