### ISSUE TITLE
End Time is an integer

### ISSUE THREAD

**Issue by Yadunund** [open-rmf/rmf-web#393]
`rmf-web` : `main` branch

The `End Time` for a task as populated in the Robots tab seems to be an integer. It is however correctly populated in the card on the right side panel.

![image](https://user-images.githubusercontent.com/13482049/120888316-40061a80-c62a-11eb-8d40-108b6f16ec4f.png)

**Comment by ChawinTan** [comment]
I think this is to represent the duration needed for the tasks since the value is `end_time - start_time`. If that's the case then changing the title to something more appropriate would do. Maybe @vallq can clarify the original intention?

**Comment by vallq** [comment]
hi sorry, I missed this. but the original design was for this to be an ETA (duration) instead of End Time. The integer right now is an estimate in seconds with the start and end time

**Comment by koonpeng** [comment]
fixed by #394
