### ISSUE TITLE
Implement a more robust and efficient ways to upload tasks

### ISSUE THREAD

**Issue by ChawinTan** [open-rmf/rmf-web#418]
## Feature request

Explore more robust and efficient ways to upload tasks.

### Description

Right now, tasks can be uploaded via json or txt files in an array of json objects and it may not be a practical format for jobs like these in an actual production. More likely, files would probably be in the form of and excel file, csv file or files with a fix layout that is generated manually or from a db, for example.

I feel like we should add the following features in addition to what is already supported:

1. Support for more practical file types, eg: excel, csv files
2. Specify a format for files to be uploaded. For example, the order of the fields, typing of the field etc ...
3. A converter unit to convert all these files to the final format to be sent to the api call.

### Implementation considerations

What are the different ways that operators might want to upload a task/batch of tasks?

**Comment by koonpeng** [comment]
Paging @codebot on comments regarding excel support.

> Specify a format for files to be uploaded. For example, the order of the fields, typing of the field etc ...

I'm not sure if we should have this level of flexibility. Users don't want to specify these fields before uploading, admins don't want to configure these before uploading files can work. It can also easily lead to many problems, new fields in tasks or a modified field type will break these configurations.

**Comment by mdfesto** [comment]
@koonpeng we don't need excel support, per se, but we need the ability for mass upload of tasks. Recommend .csv or some other text based format. You can imagine in some delivery scenarios, there will be many hundreds (maybe thousands?) of scheduled tasks per week. Ultimately we need the ability for both (1) mass upload for pre-scheduled tasks and (2) ad hoc requests.

**Comment by aaronchongth** [comment]
This can be achieved using the task scheduler now
