### ISSUE TITLE
Incorrect preview of batch tasks

### ISSUE THREAD

**Issue by Yadunund** [open-rmf/rmf-web#421]
### Required information:

- Operating system and version:
  - Ubuntu 20.04  
- OpenRMF installation type:
  - Source 
- OpenRMF version or commit hash
  - main 
- ROS distribution and version:
  - Foxy 
- ROS installation type:
  -  Binaries
- Package or library, if applicable:
  - rmf-web

### Description of the bug

When a batch of tasks is uploaded, the preview of the tasks does not seem to reflect some of the request parameters properly. For example, with the `office` world, when I upload a file containing 
```
[
  {"task_type":1, "start_time":0, "priority":1, "description": {"num_loops":5, "start_name":"pantry", "finish_name":"supplies"}},
  {"task_type":1, "start_time":0, "priority":0, "description": {"num_loops":10, "start_name":"supplies", "finish_name":"lounge"}}
]
  
```
where one loop task has 1 priority and 5 loops while the other has 0 and 10 resp, the preview does not reflect these parameters. However, when I hit submit and click on the task card, it does seem to have the right details.

https://user-images.githubusercontent.com/13482049/124564400-9b1e6d80-de73-11eb-8656-ab99910757ae.mp4

**Comment by koonpeng** [comment]
fixed by #424
