### ISSUE TITLE
Common library package for E2E tests

### ISSUE THREAD

**Issue by vallq** [open-rmf/rmf-web#439]
> @vallq @koonpeng Many of the functionalities that are used in this package are also used in the `dashboard-e2e`. Does anyone have any suggestions not to repeat this code? any ideas:
> 
> * Place the e2e-dashboard and e2e-reporting under an e2e folder?
> * Create an additional package as a common factor to use in these two packages?

I prefer a common lib package. Some build systems like react scripts are known to complain when trying to import a module outside of the root source dir.

_Originally posted by @koonpeng in https://github.com/open-rmf/rmf-web/issues/417#issuecomment-874633642_

**Comment by matiasbavera** [comment]
Adding to this issue. 

If we want to run locally the dashboard-e2e and the reporting-e2e at the same time, I think we can have problems because the keycloak has the same port.

**Comment by aaronchongth** [comment]
Closing stale issue regarding e2e. Reporting has been removed via https://github.com/open-rmf/rmf-web/pull/628 as well.
