### ISSUE TITLE
Dashboard crash on mouse scroll wheel.

### ISSUE THREAD

**Issue by matiasbavera** [open-rmf/rmf-web#445]
## Status

Need reproducible test case.

## Bug report
The Dashboard crash on the mouse scroll wheel. Happened while we were trying to zoom into the map with the mouse scroll wheel.

### Description of the bug

From @youliangtan I get this error sometimes. (running on a larger world map)

### Screenshots

![image](https://user-images.githubusercontent.com/11761240/126651601-f6718885-d780-49b9-ac7a-3ae069e34e46.png)

![image](https://user-images.githubusercontent.com/11761240/126651802-fd3f7ad5-47bf-4c66-9eeb-2f863406acb1.png)
![image](https://user-images.githubusercontent.com/11761240/126651762-8cfa827a-397d-4d52-8539-c8030c965626.png)

### Additional information

From @ChawinTan : There were some cases where mapRefs became undefined after a while.

**Comment by youliangtan** [comment]
Thanks for debugging this issue. Great to hear that this won't happen in the new `main` branch. Yes, we can close this ticket if this issue doesn't resurface again.
