### ISSUE TITLE
Remove IP field from DB and keep the time on the date range

### ISSUE THREAD

**Issue by matiasbavera** [open-rmf/rmf-web#448]
Only two comments, not directly related to reducing log size:
1. The time range to query the reporting-server gets refreshed every time we change tabs on the left-hand side panel. It might be helpful to persist the time range.
2. Currently, the IP address that is being logged in the reporting-server is the ip address of the reverse proxy used in a kubernetes deployment. Not sure if there is a way to "fix" this, but currently the ip field is "non-informational" with this ( arguably common) deployment architecture.

_Originally posted by @cnboonhan in https://github.com/open-rmf/rmf-web/issues/430#issuecomment-885578623_

**Comment by ChawinTan** [comment]
Merged
