### ISSUE TITLE
Possible missing dashboard dependency for icon setup

### ISSUE THREAD

**Issue by cnboonhan** [open-rmf/rmf-web#454]
When installing icons for the dashboard, I am missing the inquirer dependency: https://github.com/open-rmf/rmf-web/blob/main/packages/dashboard/scripts/setup/setup.js#L2 . I don't think this is specified in the dashboard package.json file: https://github.com/open-rmf/rmf-web/blob/main/packages/dashboard/package.json

**Comment by koonpeng** [comment]
fixed by #462
