### ISSUE TITLE
Routing bugs for reporting package when deployed

### ISSUE THREAD

**Issue by cnboonhan** [open-rmf/rmf-web#459]
Once the `reporting` package is deployed, various routing bugs seem to present. I am comparing the expected behavior of the `reporting` package, with the `dashboard` package. 

Based on commit https://github.com/open-rmf/rmf-web/commit/1044b404bede5163c8ff10238ca1b86b3d9be06c

When I visit:
https://example.com/reporting
Expected Behavior:
https://example.com/reporting routes to https://example.com/reporting/login
Actual Behavior:
Redirect loop between reporting and /reporting/ : Attached is image of this

![redirect_loop](https://user-images.githubusercontent.com/12628669/127991624-a60c1caf-b337-4bbf-99ba-3ec0cbe417e9.png)

When I visit:
https://example.com/reporting/
Expected Behavior:
https://example.com/reporting/ routes to the "Are you lost? Go To Login" page
Actual Behavior:
Redirects to https://example.com/reporting/login

When I visit:
https://example.com/reporting/login
Expected Behavior:
Reporting "page" is loaded as if i visited https://example.com/reporting
Actual Behavior:
404 not found

**Comment by koonpeng** [comment]
fixed by #460
