### ISSUE TITLE
Incorrect start_time visualizations in dashboard

### ISSUE THREAD

**Issue by cnboonhan** [open-rmf/rmf-web#465]
We had some odd issues behavior in the dashboard where the wrong start_time was being visualized in the dashboard. 

On further inspection it seemed like there are multiple start_time values in the tasksummary database message definition, would it be possible that the wrong field was used?

The following is an illustrative example of a tasksummary ( not the exactly the one that we observed as giving the bug, but hopefully helpful for reproducing the error )

```
 kubectl exec -it rmf-server-db-55c77cf6f8-h99c7 /bin/bash
psql -U rmf-server
SELECT * FROM tasksummary;
```
gives one or more entries like the following:
```
{
  "state": 2,
  "status": "",
  "task_id": "ReturnToChargerafd8cc",
  "end_time": {
    "sec": 1628242222,
    "nanosec": 196748700
  },
  "fleet_name": "robot",
  "robot_name": "robot",
  "start_time": {
    "sec": 1628241978,
    "nanosec": 572199859
  },
  "task_profile": {
    "task_id": "ReturnToChargerafd8cc",
    "description": {
      "loop": {
        "task_id": "",
        "num_loops": 0,
        "robot_type": "",
        "start_name": "",
        "finish_name": ""
      },
      "clean": {
        "start_waypoint": ""
      },
      "station": {
        "task_id": "",
        "place_name": "",
        "robot_type": ""
      },
      "delivery": {
        "items": [],
        "task_id": "",
        "pickup_behavior": {
          "name": "",
          "parameters": []
        },
        "dropoff_behavior": {
          "name": "",
          "parameters": []
        },
        "dropoff_ingestor": "",
        "pickup_dispenser": "",
        "pickup_place_name": "",
        "dropoff_place_name": ""
      },
      "priority": {
        "value": 0
      },
      "task_type": {
        "type": 0
      },
      "start_time": {
        "sec": 0,
        "nanosec": 0
      }
    },
    "submission_time": {
      "sec": 0,
      "nanosec": 0
    }
  },
  "submission_time": {
    "sec": 0,
    "nanosec": 0
  }
}
```

**Comment by koonpeng** [comment]
multiple `start_time` is normal as that is the ros message definition, do you have examples or a reproducible scenario of this bug? Make sure the sim time settings matches that of rmf

The most likely cause is wrong use of sim time in some code paths or failing to account for timezones.

**Comment by cnboonhan** [comment]
i'm unable to reproduce this locally. I'll close this for now, and reopen if I / anyone encounters this again.
