### ISSUE TITLE
Failed Tasks remain in task panel represented as queued Station Tasks

### ISSUE THREAD

**Issue by cnboonhan** [open-rmf/rmf-web#483]
It seems that when when a Task fails to be bid for, the task in rmf-web task panel is now represented as a "Queued Station Task"? Attached is a screenshot showing this on the right side panel. Loop1 was a task that was failed to be bid for, as seen on the top left panel:

```
[INFO] [1630303956.510534202] [rmf_dispatcher_node]: Add Task [Loop1] to a bidding queue
[WARN] [1630303958.548463987] [rmf_dispatcher_node]: Dispatcher Bidding Result: task [Loop1] has no submissions during bidding, Task Failed
```
![Screenshot from 2021-08-30 14-15-12](https://user-images.githubusercontent.com/12628669/131294046-f60a6531-42e1-415b-9f7d-a07f08332bde.png)

**Comment by ChawinTan** [comment]
I think this bug has been known for a while and its because the taskSummary message is populated in an incomplete manner. The temp fix is cherry-picked into `rmf_ros2/throwaway/demo` I believe but it seems that the fix has not been merged into main yet.

**Comment by Yadunund** [comment]
@youliangtan in `rmf-web/throwaway/demo`, the api-server subscribes to `filtered_task_summaries`. But I think we updated the dipatcher in `rmf_ros2/main` to publish to `dispatcher_ongoing_tasks` instead? Should we update the api-server in`rmf-web/main` to subscribe to this topic?

**Comment by youliangtan** [comment]
Yes. Some changes need to be made in the api server since `dispatcher_ongoing_tasks` is using `Tasks` ( a list of task summaries) as oppose to `filtered_task_summaries` using `TaskSummaries`. Let me try to take this task.

**Comment by Yadunund** [comment]
Oh i see. I assumed `dispatcher_ongoing_tasks` was just a renaming of `filtered_task_summaries`. Is there a reason for the difference?

**Comment by cnboonhan** [comment]
@youliangtan  it seems this has been solved, now that i test with latest main. I'll close this right now, but do re-open this if I am mistaken.
