### ISSUE TITLE
Batch tasks submitted to dispatcher in reverse order

### ISSUE THREAD

**Issue by Yadunund** [open-rmf/rmf-web#484]
It seems that when a batch task file containing tasks [A, B, C] is uploaded, the dashboard submits the tasks to the dispatcher in the reverse sequence, ie, C->B->A. This causes minor inconvenience with scripting scenarios for demos.

**Comment by koonpeng** [comment]
```tsx
  const submitTasks = React.useCallback<Required<TaskPanelProps>['submitTasks']>(
    async (tasks) => {
      if (!tasksApi) {
        throw new Error('tasks api not available');
      }
      await Promise.all(tasks.map((t) => tasksApi.submitTaskTasksSubmitTaskPost(t)));
      handleRefresh();
    },
    [tasksApi, handleRefresh],
  );
```

Since rmf does not support batch tasks, the client is submitting the requests in parallel, the order is probably a byproduct of how the browser handles scheduling of promises. If we want to change this behavior, we will have to submit tasks in sequence which will slow down the process.

**Comment by Yadunund** [comment]
Ah I see. Thanks for explaining why this happens. Is it safe to say that the behaviour is also browser specific, ie, the same file uploaded via dashboards running on Firefox and Chrome may have different outcomes? If so we will make sure to use the same browser to upload th scenario for the demo.

**Comment by koonpeng** [comment]
Currently batch upload is unordered, so we can assume the order may be different everytime. Because we are uploading tasks in parallel, external factors like network latency may change the order as well.

**Comment by koonpeng** [comment]
I believe this is only fixed on the throwaway branch, it remains a question if we should port it to the main branch, use the current parallel impl or wait for open-rmf/rmf_ros2#115 to be implemented first and use actual batch task submissions rather than hacking around it on the client side.

**Comment by aaronchongth** [comment]
This can be achieved using the task scheduler now
