### ISSUE TITLE
dashboard: Use virtualized table and lists

### ISSUE THREAD

**Issue by koonpeng** [open-rmf/rmf-web#492]
## Feature request

#490 addresses some of the performance issue with the new building map page. For more performance improvements, we should make use of virtualized table and lists.

A virtualized table or list is a table or list that only updates the items currently visible.

**Comment by ChawinTan** [comment]
Feel like taking this up. 

Should we also only subscribe to the doors and lifts that are currently visible in the window? After taking a look i think it is more of an issue of rendering too many items in the window every interval and the subscriptions should not be a concern if we don't display the rest of the items?

**Comment by koonpeng** [comment]
> Should we also only subscribe to the doors and lifts that are currently visible in the window?

Selective subscribing would reduce bandwidth, but have higher latency, I don't think we need it as we would probably hit a UX problem before the bandwidth problem. We would need to redesign the UI as scrolling though 100s or 1000s of entites is not a good UX.

> After taking a look i think it is more of an issue of rendering too many items in the window every interval and the subscriptions should not be a concern if we don't display the rest of the items?

Yeah, react rendering of the components is the main cause of the lag.

**Comment by vallq** [comment]
Hello, I was looking at MUI components as a reference for the figma, and I realized that `Data Grid` has filtering ability along with [inbuilt virtualization](https://mui.com/components/data-grid/virtualization/), so it doesn't have to rely on the `react-virtualized` library, Might be worth considering this? Maybe this can be modified to handle the components in its individual box component as well, instead of just a list, I'm not entirely sure

**Comment by koonpeng** [comment]
> Hello, I was looking at MUI components as a reference for the figma, and I realized that Data Grid has filtering ability along with inbuilt virtualization, so it doesn't have to rely on the react-virtualized library, Might be worth considering this? Maybe this can be modified to handle the components in its individual box component as well, instead of just a list, I'm not entirely sure.

I would prefer using that if it supports an actual grid instead of just rows of data like a table. If not, then it seems like `react-virtualized` is "deprecated" and we should use `react-window` as a more modern alternative.

**Comment by ChawinTan** [comment]
> Hello, I was looking at MUI components as a reference for the figma, and I realized that `Data Grid` has filtering ability along with [inbuilt virtualization](https://mui.com/components/data-grid/virtualization/), so it doesn't have to rely on the `react-virtualized` library, Might be worth considering this? Maybe this can be modified to handle the components in its individual box component as well, instead of just a list, I'm not entirely sure

I think Data grid does not support the cell like grids that we have so we would have to use `react-windows` or some virtualization package to do that for the cell like grids.
