### ISSUE TITLE
To use Hotel world for default testing

### ISSUE THREAD

**Issue by aaronchongth** [open-rmf/rmf-web#497]
### Description

In order to test behaviors handling larger scale and multi-level maps, the [Hotel world](https://github.com/open-rmf/rmf_demos/tree/main/rmf_demos_maps/maps/hotel), should be used for default testing, instead of Office.

**Comment by cnboonhan** [comment]
https://github.com/open-rmf/rmf-web/issues/510

you may encounter this issue ( i did )

**Comment by aaronchongth** [comment]
@vallq Per VC, @youliangtan would take the lead in setting up the Hotel world for default testing. The prototype would be on Figma, https://github.com/open-rmf/rmf-web/issues/498, you can coordinate to use the same map images, or make changes if needed.

**Comment by aaronchongth** [comment]
Per VC, this is blocked by https://github.com/open-rmf/rmf-web/issues/532, we would like any multi-floor issues to be resolved before we switch to Hotel as our default testing world.
