### ISSUE TITLE
dashboard: Overview tab to replace Building tab as default

### ISSUE THREAD

**Issue by aaronchongth** [open-rmf/rmf-web#502]
### Description

As per VC, it would be extremely useful to users to have a deployment Overview tab, where all the states and information of the deployment are visible. This will replace the Building tab as the default tab when logged into the dashboard.

### Implementation considerations

* This Overview tab will not have any capabilities to issue commands or tasks.

* It is almost impossible to squeeze all the states and possible statistics of the whole deployment into a single tab, therefore consider having filters or further tabs in each separate panel in the Overview Tab, for example filtering robots that are currently charging, having an infrastructure panel where there are different tabs for doors and lifts, etc.

* Should be extensible to future statistics implementations, as we might want to view robot downtime/uptime, total floor area cleaned, number of times this door was accessed, etc.

* The map in the overview tab will still be a interactive map.

**Comment by cnboonhan** [comment]
curious if this overview tab is essentially a buildings tab with a "lock" enabled to prevent any inputs from the user ? if in that case, i'm wondering if its less redundant to have a single tab, with an additional option to restrict user input

**Comment by aaronchongth** [comment]
That's a good way to describe it, @cnboonhan. From what was discussed during our meeting, it sounds like the purpose of the Overview tab was to be something almost entirely passive, left to be displayed on a big screen somewhere for operators, for example.

The "lock" feature could possibly work, the only downsides I can think of are

* Screen space constraint, with more buttons and drop-down lists, we might lose precious screen space for more delicious stats :bar_chart: 
* It might be duplicated effort too, since we have the Robot, Infrastructure, Task, Scheduled Task tab, which in my opinion would be much better candidates to issue commands from

I'd be curious to know what the rest of the web team thinks too, maybe they'd be able to weigh in on implementation complexity. Let me know what you think.

**Comment by vallq** [comment]
@aaronchongth 
When you mean 'dynamic map', is it supposed to be interactable (zoom control, clicking on robot / infrastructure icons etc.)

My understanding from the prev meeting was that the overview should be more of a statistical board with different readings / general information of where all the robots are, the tasks they are assigned to. And the map is locked / passive, because we don't expect users to interact with it. 

Then the individual tabs will have more detailed information and the interactive map for the robots tab. So the same goes for infrastructure control; which is executed within the proposed infrastructure tab.

I would expect that the robots and infrastructure tabs would have a map each...?

**Comment by aaronchongth** [comment]
@vallq thanks for checking! Sorry for using the wrong terminology, for any mention of "dynamic map", I meant the interactive map. I'll edit my write-ups to use the correct term.

> My understanding from the prev meeting was that the overview should be more of a statistical board with different readings / general information of where all the robots are, the tasks they are assigned to. And the map is locked / passive, because we don't expect users to interact with it.

Yup! During VC, we initially suggested the use of a static map for the Overview tab, (much like a car racing game side map, for example). However based on the feedback, the static map's features would just be a subset of the current dynamic map, and it might make more sense to continue using and building on top of it, for example options to lock a view, or disable zooming, etc.

> Then the individual tabs will have more detailed information and the interactive map for the robots tab. So the same goes for infrastructure control; which is executed within the proposed infrastructure tab.

You are absolutely right! We would look for the Robot and Infrastructure tabs to have an interactive map each. As for the minute details about how the maps should work across tabs, I'd like to hear you and the rest of the web team's advice on this. Would it be ill advised to have 3 separate interactive maps in the dashboard? For example, Overview tab has its map locked on to view Zone 1, Robot tab is currently centered around Robot1, Infrastructure tab is currently centered around Lift1.

**Comment by cnboonhan** [comment]
worth considering ( in this context ) how this will work for multiple levels, since its non-interactive. We can have multiple screens, each focused on a different level, or perhaps some sort of "slideshow" loop through different levels

**Comment by aaronchongth** [comment]
@cnboonhan I think that is a freaking good idea. At the moment I think we are looking at not entirely non-interactive, call it minimally interactive, if you will. I think a simple tab toggle for each floor on the side of the map will work well.

Slideshow or multiple Overview tabs should definitely be in the roadmap when we start dealing with more multi-level scenarios, this could be re-visited when we get https://github.com/open-rmf/rmf-web/issues/497 merged.

**Comment by koonpeng** [comment]
We should start with a figma prototype.

**Comment by vallq** [comment]
![image](https://user-images.githubusercontent.com/28668944/134868407-d88de490-7ef4-4725-849a-00b6545e37f9.png)

Components:
1. Map with panning, zoom and level control
2. AMRs and Infrastructure summary (Robot State, Door State, Lift State etc)
3. Summary of Tasks (Using color to identify states)
4. Data visualization (Action: confirm the types of viz needed)
- Breakdown of Job Types
- Avg Time spent at charging docks
- Time Spent on Tasks
- Others??

**Comment by aaronchongth** [comment]
Some feedback from Show-and-tell,
* Task panel, to have 3 columns, `Active`, `Queued`, `Completed`, with the tasks colored depending on the states like how is done in the prototype
* For the information panel (robots, doors, lifts, workcells), we can potentially split into 3 rows (Robots, Infrastructure, Workcells), and have horizontal scrolling in the event that there are more items than the row can fit.
* We can focus on those 3 types of stats you mentioned for now, the other stats can be implemented and added down the road.
* There is interest for configurable panels and layouts, but that should be a stretch goal down the road.

**Comment by vallq** [comment]
![figma-info-panel](https://user-images.githubusercontent.com/28668944/136179018-52762575-386a-44e9-8c2d-7d58ae43b908.gif)
Maybe need better naming of the panel, and would all maps have at least 1 workcell...? I didn't include the workcell info for now

**Comment by aaronchongth** [comment]
Closing as this is no longer in our upcoming roadmap.
