### ISSUE TITLE
dashboard: Clicking a component in panels moves interactive map to center on its icon

### ISSUE THREAD

**Issue by aaronchongth** [open-rmf/rmf-web#503]
### Status

Per VC, this is blocked by the implementation of different Tabs, 
- [x] https://github.com/open-rmf/rmf-web/issues/504
- [ ] https://github.com/open-rmf/rmf-web/issues/505
- [ ] Implement settings tab (TBC)

but can be started on independently when each tab is completed.

### Description

It is sometimes difficult for users to find the object of interest (robot, door, lift, etc) on the interactive map if the scale of the map is large. Consider centering the interactive map onto the object's icon when the object is clicked on the other panels, in the tabs that the interactive map exists.

### Implementation considerations

* There might be users who do not want this feature, as they have zoomed out to make the whole map visible, this might make them need to zoom out every time they click on an object to check its state. Consider adding a toggle in the settings if this feature should be enabled.

**Comment by koonpeng** [comment]
We should start with a figma prototype first.

**Comment by vallq** [comment]
I think @ChawinTan has built this centering feature in one of the branches previously? Correct me if I am wrong!

But also there would be the design issue of one-click performing 2 different interactions, similar to what we discussed previously for the task panel right, @koonpeng? if clicking on a component shows information on a side panel and performs the centering on the map.

![image](https://user-images.githubusercontent.com/28668944/133952023-5ea75583-3fb8-4c66-b206-15189a1cf885.png)
I foresee it would look something like this? the space below the map is empty for now, perhaps the toggle mentioned could be here, or it can be in the settings drawer

**Comment by aaronchongth** [comment]
> We should start with a figma prototype first.

Agreed! @koonpeng, I just added this line in the self-check, let me know what you think, https://github.com/open-rmf/rmf-web/pull/513

> I think @ChawinTan has built this centering feature in one of the branches previously? Correct me if I am wrong!

Yup! It is in one of the branches and it was previously blocked by the removal of the omni-panel. I think the individual tabs should be a priority, before the feature for centering of icons on itneractive maps can be added in.

**Comment by aaronchongth** [comment]
Per VC, this is blocked by the implementation of different Tabs, 
- [ ] https://github.com/open-rmf/rmf-web/issues/504
- [ ] https://github.com/open-rmf/rmf-web/issues/505

but can be started on independently when each tab is completed.

**Comment by vallq** [comment]
![figma-centering-of-icon](https://user-images.githubusercontent.com/28668944/136177634-dc726f4e-3f0e-4e3c-92e9-239f56306675.gif)

**Comment by ChawinTan** [comment]
@val and @aaronchongth  Will the object be centered when it is clicked on the map itself or when the cell associated with it in the panel is clicked on?

The animation suggest the former but my understanding of this feature is the latter.

**Comment by aaronchongth** [comment]
Oh good catch! I think we would like the latter as mentioned by @ChawinTan. The implementation would hopefully be just a migration from our other feature branches. @vallq could you help update the prototype when you have some free cycles?

**Comment by vallq** [comment]
Oh okay I always thought it was the former with the clicking of icons, got it!

**Comment by ChawinTan** [comment]
The zooming logic is implemented in both panels, now pending both to be merged
