### ISSUE TITLE
dashboard: Interactive map in Robot tab

### ISSUE THREAD

**Issue by aaronchongth** [open-rmf/rmf-web#504]
### Description

The same interactive map seen in the Building/Overview(https://github.com/open-rmf/rmf-web/issues/502) tab, should also be applied to the Robot tab.

### Implementation considerations

This will allow users to zoom in, see trajectories of any specific robot as well as center the map onto the robot. (https://github.com/open-rmf/rmf-web/issues/503)

**Comment by koonpeng** [comment]
We should start with a figma prototype first.

**Comment by aaronchongth** [comment]
Prototype on Figma for reference,
![image](https://user-images.githubusercontent.com/5383623/134844202-7f986841-2269-4bb5-bcb3-836a4398b265.png)

**Comment by aaronchongth** [comment]
Some feedback from show-and-tell,
* There wasn't any input as to what should go into the empty panel below the interactive map, consider making the map fill up the entire column.

**Comment by aaronchongth** [comment]
Prototype of Figma is looks great! This task is ready for assignment.
