### ISSUE TITLE
dashboard: Infrastructure tab

### ISSUE THREAD

**Issue by aaronchongth** [open-rmf/rmf-web#505]
### Description

Similar in function as the Robot tab, the Infrastructure tab should allow users to monitor the different states of all the infrastructure involved in the deployment, i.e. doors, lifts, etc.

### Implementation considerations

* To have a interactive map similar to Building/Overview tab, and the upcoming Robot tab revision(https://github.com/open-rmf/rmf-web/issues/504).
* Clicking onto the components will center the said interactive map, similar to https://github.com/open-rmf/rmf-web/issues/503.
* To have the same amount of control as the panels in the Building tab as of now, 
![image](https://user-images.githubusercontent.com/5383623/133024061-3df23184-94be-4c64-9b70-3b488ddf71aa.png)

**Comment by koonpeng** [comment]
We should start with a figma prototype first.

**Comment by vallq** [comment]
![image](https://user-images.githubusercontent.com/28668944/133952301-62292df7-8fa5-44ca-b070-06feb379e786.png)
Figma design is up to date with the current development progress. I think this tab would not have as many changes other than naming of the tab? and perhaps other forms of visualization/controls.

**Comment by aaronchongth** [comment]
@vallq the prototype for this looks great! We can go ahead with the implementation, would you like to pick this up?

**Comment by vallq** [comment]
Okay, sure!

https://user-images.githubusercontent.com/28668944/136174663-c6fc6de9-33b1-4466-885e-fbac1c4acb1c.mp4

Current update, fitting more blocks within each row
