### ISSUE TITLE
[ Discussion ] Purpose of Cancel and Ok button in Lift Form?

### ISSUE THREAD

**Issue by cnboonhan** [open-rmf/rmf-web#511]
I'm wondering if anyone has any thoughts on the UI for the Lift Form? Apologies if there is a design document I grossly skipped over.
![liftform](https://user-images.githubusercontent.com/12628669/133435170-0cc44c71-9423-417f-8ffb-eb9a09aca21a.png)

* Firstly I noticed the difference between a Task Request  ( on the task panel )and a Lift Request, is that the Lift Request form does not automatically close when submitted. This may make the user confused and click to submit multiple requests.
* The Level field seems to switch after each request to the current level of the Lift. As a result of the combination of this point and point 1, the user can easily accidentally send the lift to their target level, and back to the current level.
* Specifically, what is the difference between the Request and Ok button? they seem to do the same thing. As a result, the user may accidentally send "contradictory" lift requests by trying to use the ok button to close the form.
* What is the use of the Cancel button? Would the expected behavior to send the lift back to the previous level it was on? Or is it equivalent to clicking the cross on the top right of the form?

Example of user accidentally messing up their submission:

https://user-images.githubusercontent.com/12628669/133436020-18273f25-b118-48b0-a601-1d04ab1e5bb8.mp4

**Comment by ChawinTan** [comment]
I think this was my oversight when I shift the lift request form to the `confirmation-dialog` component which is currently the default that we use for anything requires a dialog box. 

Will work on it once I finish whatever I have on hand.
