### ISSUE TITLE
dashboard: on-screen alert notification

### ISSUE THREAD

**Issue by koonpeng** [open-rmf/rmf-web#517]
### Description

In-band notification for certain events (e.g. when a robot completes a task or gets stuck).

There was a system summary panel in the works, but that is discarded because omnipanel is gone now. Need a figma prototype before we can implement the frontend.

### Implementation considerations

There is a health status api in the api server, that is made when we were working on the system summary panel because of lack of certain features in rmf. The make-shift health status api is not ideal as it can only perform detect basic checks like heartbeats, moving forward, there should be a health api at the rmf level to detect more specific problems (e.g. robot motor failure etc). Related issue open-rmf/rmf_ros2#123.

**Comment by aaronchongth** [comment]
Implemented in https://github.com/open-rmf/rmf-web/pull/664 and https://github.com/open-rmf/rmf-web/pull/694.

However long term goal will leveraging something that has more capabilities like https://prometheus.io/
