### ISSUE TITLE
Performance issue with large marker counts on firefox

### ISSUE THREAD

**Issue by cnboonhan** [open-rmf/rmf-web#521]
Current performance of rmf-web dashboard on maps with large number of markers degrades significantly. Attached is a video of the airport terminal world + commit 653138d9dbfe3524c32299f227e2a5afce1d94a7 of rmf-web

* The latency of the zoom in, zoom out feature is quite high, as well as general panning actions
* On removing the waypoint markers by unchecking them on the sidebar, performance improves significantly. ( around 1 min mark in the video )
* changing tabs resets this waypoint marker removal, degrading performance again
* 
# Conclusions so far
It seems that the most likely cause of this issue is outside of rmf-web, and browser dependent. Specifically, Chrome 94 does not encounter this issue, while Firefox 92 does.  The discussion on this can be followed [here](https://github.com/open-rmf/rmf-web/pull/523) and the current conclusion [here](https://github.com/open-rmf/rmf-web/pull/523#issuecomment-935634087).

This video documents the expected lag behavior when running on Firefox 92, and does not occur on Chrome 94.

https://user-images.githubusercontent.com/12628669/136307904-5ce653ea-4be1-42ab-9fa8-53064878d94d.mp4

## Details
Both browsers were tested with the same computer setup. Attached are the following information:
- OS and Hardware details
- chrome://gpu google chrome feature report
- about:support firefox feature report

[#521_details.zip](https://github.com/open-rmf/rmf-web/files/7298121/521_details.zip)

**Comment by aaronchongth** [comment]
I do experience some latency during zooming and resizing of icons and labels, do you think it is possible for us to have the waypoints disabled by default? Or if that is a good solution at all?

**Comment by koonpeng** [comment]
@cnboonhan Can you check if this PR helps?

**Comment by cnboonhan** [comment]
To follow up, it seems the issue is firefox specific, from discussions in #523 

```
The setTimeout is in the firefox profiling is from leaflet, there isn't much we can do except rewriting the map to use a canvas-based library. It's probably due to some firefox bug or lack of gpu accleration.
```
