### ISSUE TITLE
api-server: Unclosed socket warnings in tests

### ISSUE THREAD

**Issue by koonpeng** [open-rmf/rmf-web#539]
## Bug report

The api-server tests always outputs a bunch of unclosed socket warnings

```
.................................../usr/lib/python3.8/abc.py:102: ResourceWarning: unclosed <socket.socket fd=22, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56394), raddr=('127.0.0.1', 8000)>
  return _abc_subclasscheck(cls, subclass)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
................../usr/lib/python3.8/copy.py:263: ResourceWarning: unclosed <socket.socket fd=128, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56454), raddr=('127.0.0.1', 8000)>
  args = (deepcopy(arg, memo) for arg in args)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
..../usr/lib/python3.8/copy.py:161: ResourceWarning: unclosed <socket.socket fd=143, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56474), raddr=('127.0.0.1', 8000)>
  rv = reductor(4)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
..../usr/lib/python3.8/copy.py:210: ResourceWarning: unclosed <socket.socket fd=157, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56494), raddr=('127.0.0.1', 8000)>
  y = [deepcopy(a, memo) for a in x]
ResourceWarning: Enable tracemalloc to get the object allocation traceback
.../usr/lib/python3.8/inspect.py:2821: ResourceWarning: unclosed <socket.socket fd=171, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56518), raddr=('127.0.0.1', 8000)>
  params = OrderedDict(((param.name, param)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
.............../home/koonpeng/.local/lib/python3.8/site-packages/fastapi/utils.py:65: ResourceWarning: unclosed <socket.socket fd=197, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56572), raddr=('127.0.0.1', 8000)>
  return response_field(field_info=field_info)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/koonpeng/.local/lib/python3.8/site-packages/fastapi/utils.py:65: ResourceWarning: unclosed <socket.socket fd=202, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56578), raddr=('127.0.0.1', 8000)>
  return response_field(field_info=field_info)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/koonpeng/.local/lib/python3.8/site-packages/fastapi/utils.py:65: ResourceWarning: unclosed <socket.socket fd=204, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56586), raddr=('127.0.0.1', 8000)>
  return response_field(field_info=field_info)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/koonpeng/.local/lib/python3.8/site-packages/fastapi/utils.py:65: ResourceWarning: unclosed <socket.socket fd=206, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56592), raddr=('127.0.0.1', 8000)>
  return response_field(field_info=field_info)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/koonpeng/.local/lib/python3.8/site-packages/fastapi/utils.py:65: ResourceWarning: unclosed <socket.socket fd=208, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56598), raddr=('127.0.0.1', 8000)>
  return response_field(field_info=field_info)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.8/abc.py:102: ResourceWarning: unclosed <socket.socket fd=185, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56540), raddr=('127.0.0.1', 8000)>
  return _abc_subclasscheck(cls, subclass)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
../usr/lib/python3.8/asyncio/base_events.py:431: ResourceWarning: unclosed <socket.socket fd=216, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56652), raddr=('127.0.0.1', 8000)>
  task = tasks.Task(coro, loop=self, name=name)
```

These sockets come from socketio, more investigation is needed to find out how to remove these.

### Required information:

- Operating system and version:
  - 
- OpenRMF installation type:
  - 
- OpenRMF version or commit hash
  - 
- ROS distribution and version:
  - 
- ROS installation type:
  - 
- Package or library, if applicable:
  -

**Comment by cnboonhan** [comment]
I do get the following flaky errors as well:

```
.ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ubuntu/rmf-web/.venv/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/ubuntu/rmf-web/.venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/ubuntu/rmf-web/.venv/lib/python3.8/site-packages/engineio/async_drivers/asgi.py", line 58, in __call__
    await self.engineio_server.handle_request(scope, receive, send)
  File "/home/ubuntu/rmf-web/.venv/lib/python3.8/site-packages/socketio/asyncio_server.py", line 385, in handle_request
    return await self.eio.handle_request(*args, **kwargs)
  File "/home/ubuntu/rmf-web/.venv/lib/python3.8/site-packages/engineio/asyncio_server.py", line 260, in handle_request
    socket = self._get_socket(sid)
  File "/home/ubuntu/rmf-web/.venv/lib/python3.8/site-packages/engineio/server.py", line 619, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
```

do you think they are related?

**Comment by koonpeng** [comment]
Thats weird, usually session disconnected would mean the socket is closed, but it could mean the engineio session, and maybe the socket is still open.

**Comment by cnboonhan** [comment]
so sorry, this fell off my mind. I believe this is not a serious issue. I suspect error appears due to race conditions between the socket opening / closing the built-in checks for them from the requests library. unittest starts and stops the api-server multiple times to run tests, realistically in a non-test environment, we wont be doing such repeated start/stop. 

Attached is a recording of a unittest run. On the left, we can see the error messages. The rightmost column is the command ` watch -n 0.1 "ss -tulpn | grep 8000"` which we will use to watch the api-server processes.

We can observe that the errors only appear for processes with port 8000, that is, the api-server. If something bad was happening ( due to unclosed sockets ) i believe this will evidenced on the right column as a buildup of processes, or a single process stuck. This does not appear to be true since we can see that at any time, only one process is live, and the process is rapidly refreshed as seen by the changing file descriptor.  

https://user-images.githubusercontent.com/12628669/141746646-15208049-396e-4317-aedb-24eba8930ec5.mp4

Further evidence online seems to point to this: https://github.com/psf/requests/issues/3912#issuecomment-284328247
We could consider filtering out these errors?

**Comment by koonpeng** [comment]
The linked post mentions closing the session explicitly when ending the tests.

**Comment by cnboonhan** [comment]
unfortunately, i spent quite a bit of time poking around but couldn't reasonably distinguish what exactly is the mechanism where this error pops up. From exploring the socketio/engineio API it seems like sessions are closed consistently. 

I did manage to find that if we comment out this [line](https://github.com/miguelgrinberg/python-engineio/blob/main/src/engineio/client.py#L223) which removes a engineio client from a global [list] on calling the disconnect (https://github.com/miguelgrinberg/python-engineio/blob/main/src/engineio/client.py#L24), the ResourceWarning errors disappear.  I suppose that means that client side sockets are not properly closed, but inspecting sockets using `ss -tulpn` shows that the open sockets are static ( do not seem to increase in number ).

**Comment by cnboonhan** [comment]
i suspect i found the right solution, which is to call `client.eio.http.close()` when cleaning up every connect attempt, which forcefully terminates the request session. I somehow missed this

**Comment by koonpeng** [comment]
Thanks for the investigation, I think this is the part which causes a race condition `https://github.com/miguelgrinberg/python-socketio/blob/main/src/socketio/client.py#L483`, it calls the eio client.disconnect with `abort=True`, so means it doesn't wait for the disconnect to finish. Does calling `client.eio.disconnect()` work as well?

**Comment by koonpeng** [comment]
actually, there is a `wait` function https://github.com/miguelgrinberg/python-socketio/blob/3bd13578c82e8a94d6b0328180606c2aefd496f1/src/socketio/client.py#L352

**Comment by cnboonhan** [comment]
I've tried `abort=False` [here](https://github.com/miguelgrinberg/python-socketio/blob/main/src/socketio/client.py#L483), as well as a wait after that line. Both dont seem to work.

Calling `client.eio.http.close()` works if put after places like https://github.com/open-rmf/rmf-web/blob/main/packages/api-server/api_server/test_sio_auth.py#L54. Its rather tedious to remember to write it everywhere though. [Event handlers](https://python-socketio.readthedocs.io/en/latest/client.html#connect-connect-error-and-disconnect-event-handlers) might be a mildly "cleaner" solution?

**Comment by koonpeng** [comment]
There should only be a couple of places which needs to be changed, most tests should be using `test_fixtures.py`. I don't think event handlers work, at least, you still need to add the handler for each socket that you create, so its not cleaner. I think we are also not using the async client, so trying to block in the event handler might lead to deadlock.
