### ISSUE TITLE
History pane, similar to tasks pane for audits

### ISSUE THREAD

**Issue by akash-roboticist** [open-rmf/rmf-web#552]
### Description
A historical log of tasks with following info, would be useful for audits by the site operations / facilities team
- user (name, rfid badge ID if any) who created the task, edits if any.
- destination(s)
- task details (eg. number of loops, dispenser, ingestor ID, Cleaning zone(s), etc)
- robot id (which performed the task)
- start, destination(s), end timestamps
- priority

### Implementation considerations
The current Tasks pane layout looks like an ideal start; the requested History tab would in addition to listing the above info, be capable of displaying filtered list based on various labels (eg. by date, robot id, user, etc). This list if is exportable (eg. to `csv`), would help the site to import task history into their programs (eg. Microsoft Excel) for analysis / performing delivery metrics

![2021-11-24_14:52:31_001](https://user-images.githubusercontent.com/7358106/143190635-d5ac547a-0b95-4fe7-a0df-853030663c16.png)

**Comment by cnboonhan** [comment]
in general it seems https://github.com/open-rmf/rmf-web/tree/main/packages/reporting-server should fit this requirement, but some gaps to address and we should probably review it to iron out user issues:

- not sure if its recorded who sent a task, this should be addressed with coming work on rmf_api_msgs. There was some discussion on adding labels for task cancellation requests: https://github.com/open-rmf/rmf_api_msgs/blob/main/rmf_api_msgs/schemas/cancel_task_request.schema.json#L18  which would bundle the keycloak username automatically. Perhaps we can extend this mechanism to task submission as well?
- I'm not sure there is a way to export a spreadsheet of tasks easily, so this might need some work
- Don't have much user data ( afaik ) on how "good" the UI is: there could be some improvements there

**Comment by koonpeng** [comment]
Should we really add a tab for history or just add features to the tasks tab? it already shows a list of all tasks, including all old tasks, but it is missing several things in the feature request:

* User, this is not available from rmf currently, we need keep a record of task requests for this to be available, but I would rather wait for the support in the new rmf api messages.
* Searching and filtering.

**Comment by aaronchongth** [comment]
Closing with
* https://github.com/open-rmf/rmf-web/pull/651
* https://github.com/open-rmf/rmf-web/pull/654
* https://github.com/open-rmf/rmf-web/pull/658
* https://github.com/open-rmf/rmf-web/pull/661
* https://github.com/open-rmf/rmf-web/pull/673
