### ISSUE TITLE
Task-Phase-Events-Logs Visualization: dashboard updates

### ISSUE THREAD

**Issue by aaronchongth** [open-rmf/rmf-web#557]
### Description

This ticket tracks the progress and discussions regarding visualizing the upcoming `Task` system on the dashboard, https://github.com/open-rmf/rmf_ros2/issues/107, which uses the new [rmf_api_msgs](https://github.com/open-rmf/rmf_api_msgs). Below is a sample state and log,

State: https://github.com/open-rmf/rmf_api_msgs/blob/main/rmf_api_msgs/samples/task_state/multi_dropoff_delivery.json
Log: https://github.com/open-rmf/rmf_api_msgs/blob/main/rmf_api_msgs/samples/task_log/multi_dropoff_delivery.json

This will be implemented
* based on the Figma prototype, https://github.com/open-rmf/rmf-web/issues/555, and will
* require the changes in `api-server`, https://github.com/open-rmf/rmf-web/issues/556.

**Comment by aaronchongth** [comment]
I've just managed to compile `temp/demo-deployment` and took a look at the progress on this task, I might be mistaken but this seems to be the progress so far, 
![image](https://user-images.githubusercontent.com/5383623/145920739-9eda6c47-af1f-4f6c-97bc-e6c68a69214f.png)

This seems to have somewhat diverged from what our prototype intended, https://github.com/open-rmf/rmf-web/issues/555, https://www.figma.com/proto/yqGAsVunCfxIcu2oHiPYsj/rmf-web?node-id=11165%3A7018&scaling=contain&page-id=0%3A1&starting-point-node-id=11165%3A7018&show-proto-sidebar=1. We will probably need to refocus our efforts on visualizing the progress of each task->phase->events, instead of how we are creating them (that will be left for afterwards :sparkles: )

**Comment by aaronchongth** [comment]
Per VC, the dashboard is reflecting the Figma prototype for the `task_state`, however the `task_log` does not seem to be available. To check:
* if the logs are not sent over from RMF
* if the dashboard is not picking up the logs from the `api_server`

**Comment by aaronchongth** [comment]
Per VC
* visualization of tree structure (task -> phase -> events) is there but remains more like a skeleton, some tidying up is required
* there are some features that remain commented out (auto-refresh, etc) due to the introduction of these features

**Comment by mayman99** [comment]
About the progress here, for the first task, the visualization is now working, we could see the event logs right now on the dashboard, but there are some issues

1.  the `between_query`, which I'm not sure how to set without hard coding it.
2. the logs are too much (sometimes the application can't handle them and freezes)
3. is it normal to have all the events in the first phase while the rest of the phases are empty?

I've still not started to make the visualization look like [the figma figure](https://www.figma.com/proto/yqGAsVunCfxIcu2oHiPYsj/rmf-web?node-id=11187%3A7263&scaling=contain&page-id=0%3A1&starting-point-node-id=11187%3A7263&show-proto-sidebar=1) yet.

**Comment by aaronchongth** [comment]
![Screenshot from 2022-01-27 02-53-26](https://user-images.githubusercontent.com/5383623/151300621-5340cb2a-eb2e-4b02-92db-2712582f60c5.png)

@mayman99 just shared the initial progress so far. We should be able to start integration testing using the event and phase indices for now.

**Comment by cnboonhan** [comment]
There was some discussion about pruning some fields in the dashboard that might now be redundant, such as the robot-table robot "start and destination location" fields. Should we park the pruning of these fields here as well, or should i make a new issue?

**Comment by aaronchongth** [comment]
I think it would be best to start a new ticket, with a few simple screenshots, since it can be reviewed independently from https://github.com/open-rmf/rmf-web/pull/573. Thanks!

**Comment by mayman99** [comment]
This issue and [the PR](https://github.com/open-rmf/rmf-web/pull/573/) are only targeting the `dashboard/tasks` , so I think as long as it doesn't involve this we can start a new issue

**Comment by aaronchongth** [comment]
Closed via https://github.com/open-rmf/rmf-web/pull/573
