### ISSUE TITLE
Duplicate event logs in task logs - api_server

### ISSUE THREAD

**Issue by mayman99** [open-rmf/rmf-web#570]
### Required information:

- Operating system and version:
   Ubuntu 20.04
- OpenRMF installation type:
  - source 
- OpenRMF version or commit hash
  - d3f5f972f0feed7878f39a51f1a2fe2948cb1e25 
- ROS distribution and version:
  - galactic 
- ROS installation type:
  - source 
- Package or library, if applicable:
  - api-server (possibly) 

### Description of the bug

Duplicate event logs.
[Logs are here.](https://gist.github.com/mayman99/534fe4ca134b578b38e628e5c1a6a5f0)

### Steps to reproduce the bug

1. Launch RMF using `ros2 launch rmf_demos office_demo.launch`
2. Launch api-server
3. start a task
4. navigate to something like `http://localhost:8000/tasks/patrol.dispatch-0/log?between=0,9999999`

**Comment by aaronchongth** [comment]
Per VC. this could be due to
* Database allowing duplicated entries
* Querying error, where duplicated log entries were returned

**Comment by mayman99** [comment]
after pulling latest rmf and rebuilding, I can't reproduce the issue right now as well as @koonpeng , I'm very confused why, the commits recent `rmf_ros2` shouldn't be related... either way I'll keep an eye just in case this issue pops up again.
