### ISSUE TITLE
Dashboard launching error

### ISSUE THREAD

**Issue by aaronchongth** [open-rmf/rmf-web#572]
### Required information:

- Operating system and version:
  -  Ubuntu 20.04
- OpenRMF installation type: 
  - source
- OpenRMF version or commit hash
  - `main`, .repos file with commit hashes: https://gist.github.com/aaronchongth/94683978e76cdf6959ff77342fbe0d31
- ROS distribution and version:
  - galactic
- ROS installation type:
  - binaries
- Package or library, if applicable:
  - `dashboard` and related to `api-client`

### Description of the bug

Error when starting dashboard,

```bash
Failed to compile.

./src/components/rmf-app/rmf-ingress.ts
Module not found: Can't resolve 'api-client' in '/home/aaron/workspaces/rmf_main/rmf-web/packages/dashboard/src/components/rmf-app'
```

### Steps to reproduce the bug

```bash
source rmf_ws/install/setup.bash
cd rmf-web
./script/bootstrap.sh

cd packages/dashboard
npm run start:react
```

### Additional information

There were some internal discussions regarding this issue on Slack already, hopefully we can track the patches and fixes along the way here.

Current workaround, mentioned by @cnboonhan,

```bash
source rmf_ws/install/setup.bash
cd rmf-web/packages/dashboard
npm run build
```

Once the compilation has [completed successfully](https://gist.github.com/aaronchongth/9b6ef67c22ed37cf86b7b03c0ef84203), 

```bash
npm run start-react
```

The dashboard launches fine now

**Comment by aaronchongth** [comment]
As for working with `prototype/task_v2-2` there were similar issues when starting the dashboard, the current workaround seems to be,

```bash
cd rmf-web
git checkout 8aecc89

./script/boostrap.sh

cd packages/dashboard
npm run build
npm run start:react
```

**Comment by koonpeng** [comment]
Thats expected as `start:react` does not automatically build the dependencies. Dependency resolution only works at the package level, so we can only add the build command to the main `start` script.

**Comment by aaronchongth** [comment]
Thanks for the explanation! Closing as resolved.
