### ISSUE TITLE
Pruning of react-component fields that no longer work in redesign_v2

### ISSUE THREAD

**Issue by cnboonhan** [open-rmf/rmf-web#575]
I would like to propose the removal of the following components in the dashboard that no longer seem to be propagated correctly in `redesign_v2`:

Checking / unchecking these checkboxes do not seem to visually change anything
![image](https://user-images.githubusercontent.com/12628669/152300302-23707a59-2d96-47d3-950d-b466ade7b400.png)

Start Location and Destination are always empty here. Active Task Duration is also not populated:
![image](https://user-images.githubusercontent.com/12628669/152300440-d7f0b412-08fa-43f8-8cd2-824bb9b92133.png)

Location and Destination are undefined here. Task progress is also always at 11%:
![image](https://user-images.githubusercontent.com/12628669/152300647-9ee7bcae-1ad0-42f0-a426-a1ed558b6e46.png)

@koonpeng  @aaronchongth  @mxgrey ?

**Comment by mxgrey** [comment]
How was progress being measured previously? I'm not sure there's any meaningful way to measure progress, tbh. Best case scenario would be to base it off of time estimates, but then we could see progress slide backwards due to delays.

**Comment by koonpeng** [comment]
> How was progress being measured previously? I'm not sure there's any meaningful way to measure progress, tbh. Best case scenario would be to base it off of time estimates, but then we could see progress slide backwards due to delays.

iirc, it was using a super naive approach of `(current_time - start_time) / (est_end_time - start_time)`.

**Comment by mxgrey** [comment]
I think we have enough information now to go back to that definition of progress, at least until we can think of something more meaningful.

**Comment by cnboonhan** [comment]
closing this to focus on merging https://github.com/open-rmf/rmf-web/pull/581
