### ISSUE TITLE
Clean up after merging prototype/task_v2-2

### ISSUE THREAD

**Issue by aaronchongth** [open-rmf/rmf-web#584]
## Moved all outstanding items from https://github.com/open-rmf/rmf-web/pull/582 to this new ticket, after merging into `main`,

* [x] Fix lint errors in react-component tests
  * components used by reporting is causing some of the lint errors, fixing these will require updating reporting to work with taskv2 as well. Alternative is to remove reporting from this repo altogether and move it to it's own repo.
* [x] Restore various tests that were commented out
  * Tests regarding components in robot pages are done.
  * Components in tasks page are still missing tests.
  * e2e tests need to be updated as well.
* [x] Fix bug where notification of failed submissions from other interfaces shows up on the dashboard.
* [x] Check that no intended edits were lost at sea :ocean: 
* [x] Clean up all the code that is no longer required
* [x] (Edited) Dashboard Delivery Form might be good to have validation to prevent invalid inputs. SKU: string, Quantity: int, > 0
* [x] 1 decimal precision for battery %

## Portions that might require attention:
* [x] react-components
  * https://github.com/open-rmf/rmf-web/tree/main/packages/react-components/lib/reports/task-summary/task-summary-report-table.tsx#L15
    * CI seems to say `task_profile: any` was unexpected
  * https://github.com/open-rmf/rmf-web/tree/main/packages/react-components/lib/reports/task-summary/utils.tsx#L5
    * CI warnings as well as commented out imports
  * https://github.com/open-rmf/rmf-web/tree/main/packages/react-components/lib/tasks/create-task.spec.tsx
  * https://github.com/open-rmf/rmf-web/tree/main/packages/react-components/lib/tasks/task-info.tsx

* [ ] dashboard
  * https://github.com/open-rmf/rmf-web/tree/main/packages/dashboard/src/components/dashboard/tests/items.ts
  * https://github.com/open-rmf/rmf-web/tree/main/packages/dashboard/src/components/permissions.ts
    * Looks like permission checking was removed for now 
  * https://github.com/open-rmf/rmf-web/tree/main/packages/dashboard/src/components/robots/robot-page.tsx
    * `FIXME: RobotTable does not know about which fleet a robot belongs to, so there is no way to distinguish between robots with the same name in different fleets, events fired by RobotTable, will be broken in that case.`
    * Ideally we would like to add a test for this as well once it has been fixed
  * https://github.com/open-rmf/rmf-web/tree/main/packages/dashboard/src/components/tasks/task-panel.tsx
  * https://github.com/open-rmf/rmf-web/tree/main/packages/dashboard/src/components/tasks/task-panel.tsx#L226
  * https://github.com/open-rmf/rmf-web/tree/main/packages/dashboard/src/components/tasks/tests/make-tasks.ts
  * https://github.com/open-rmf/rmf-web/tree/main/packages/dashboard/src/components/tasks/tests/task-panel.test.tsx
  * https://github.com/open-rmf/rmf-web/tree/main/packages/dashboard/src/stories/baseComponents/utils.tsx
  * https://github.com/open-rmf/rmf-web/tree/main/packages/dashboard/src/stories/task-panel.stories.tsx

I might have missed out some items while going through  https://github.com/open-rmf/rmf-web/pull/582. Please feel free to add to the list.

**Comment by mayman99** [comment]
I've opened [this PR](https://github.com/open-rmf/rmf-web/pull/587) to fix this issue, feel free to push directly, just mention what you would work on when you start to avoid conflicts.
atm I'm cleaning the tasks, removing extra code and un-commenting tests one by one.
