### ISSUE TITLE
[dashboard] Display last updated time in robot panel

### ISSUE THREAD

**Issue by aaronchongth** [open-rmf/rmf-web#596]
### Description

This will be helpful to monitor the liveliness of robots or fleet adapters during deployment.

Ideally this `Last updated` field will be added below the name of the robot, before the divider
![image](https://user-images.githubusercontent.com/5383623/160084691-9e1f944f-1be8-418a-87aa-b4154ed002b5.png)

**Comment by mayman99** [comment]
![Screenshot from 2022-03-28 08-28-23](https://user-images.githubusercontent.com/10261903/160339059-b5076e1a-484c-4de2-a8a8-fa1a24f139b9.png)
how does it look? @youliangtan @aaronchongth

**Comment by mayman99** [comment]
maybe I should add an "ago" :thinking:

**Comment by youliangtan** [comment]
Thanks for the fast enhancement! yeap adding an `ago` would be preferred. :bow:  
Just some design nit, can we try the "time update" wordings less alike to the robot name? (unbold with subtle font, or under the separation line, etc.).

**Comment by aaronchongth** [comment]
@mayman99, that looks so good! Yeah I will agree with @youliangtan. Let's make it `Last updated # seconds ago`, with the font be similar to this plainly
![image](https://user-images.githubusercontent.com/5383623/160350071-42865fbd-d960-4c80-bb04-e63724922c28.png)

**Comment by mayman99** [comment]
PR here #597

**Comment by aaronchongth** [comment]
Closing via https://github.com/open-rmf/rmf-web/pull/597
