### ISSUE TITLE
bootstrap script not working on latest npm

### ISSUE THREAD

**Issue by koonpeng** [open-rmf/rmf-web#599]
## Bug report

The bootstrap script no longer works with the latest npm due to https://github.com/npm/cli/issues/4552.

A temporary workaround is being added to the CI to use an older version https://github.com/open-rmf/rmf-web/pull/598. The old version can be reverted once the bug is fixed in npm.

**Comment by daichuihua** [comment]
when does this bug fixed? Is there another way to use rmf-web?

**Comment by mayman99** [comment]
This should have been fixed on main branch, do you still have it?
also a work around for now is to use an npm version older than 8.4

**Comment by daichuihua** [comment]
> This should have been fixed on main branch, do you still have it? also a work around for now is to use an npm version older than 8.4

My situation:bootstrap script can work on latest npm right now ,but "cd rmf-web/packages/dashboard" and "npm start" no work
like this:
![Screenshot from 2022-04-12 10-33-58](https://user-images.githubusercontent.com/30583933/162868529-f1239f57-576c-43ec-a9bc-55d92e3dfc32.png)
![Screenshot from 2022-04-12 10-34-25](https://user-images.githubusercontent.com/30583933/162868540-aa8a3fff-fc07-4f68-9740-9b2e1ad57469.png)
![Screenshot from 2022-04-12 10-35-23](https://user-images.githubusercontent.com/30583933/162868545-057b77da-f6c6-4cd8-a642-29cb25f9c53a.png)

**Comment by mayman99** [comment]
:thinking: could you maybe write the exact commands that you are using in each terminal?
and in the dashboard package, does running `npm run build` before the `npm run start` get you any different result?

**Comment by daichuihua** [comment]
> thinking could you maybe write the exact commands that you are using in each terminal? and in the dashboard package, does running `npm run build` before the `npm run start` get you any different result?

[](https://user-images.githubusercontent.com/30583933/162892410-7cb86e95-7af7-49ed-b46f-29c3af62452a.png)[](https://user-images.githubusercontent.com/30583933/162892444-46c77e90-17cf-4ab8-a24e-846222cab9ee.png)[](https://user-images.githubusercontent.com/30583933/162892505-28f59267-9c8b-4edb-a1ce-3b7f8ee59e9e.png)[](https://user-images.githubusercontent.com/30583933/162892516-94cf0853-7ea9-4067-b390-28af948c5171.png)1>cd rmf-web-main && cd scripts && ./bootstrap.sh (1st terminal)
![Screenshot from 2022-04-12 14-02-59](https://user-images.githubusercontent.com/30583933/162893365-1692c1f2-8148-4df9-ba64-f227de11251f.png)


2>ros2 launch rmf_demos_gz office.launch.xml server_uri:="ws://localhost:8001" (2nt terminal)
![Screenshot from 2022-04-12 14-04-37](https://user-images.githubusercontent.com/30583933/162893385-075f5b7d-268f-4415-ab01-decce3924fa6.png)


3>cd rmf-web-main/packages/dashboard && npm run start (3rd terminal)
![Screenshot from 2022-04-12 14-07-07](https://user-images.githubusercontent.com/30583933/162893410-1ac8bdf6-93c6-4025-98c2-a7be058f9e36.png)
![Screenshot from 2022-04-12 14-07-45](https://user-images.githubusercontent.com/30583933/162893430-135a6f97-45b3-4e7c-9ec1-f1be53ba13c5.png)


result:
[start:rmf-server] from tortoise import Tortoise
[start:rmf-server] ModuleNotFoundError: No module named 'tortoise'
[start:rmf-server] npm ERR! Lifecycle script start:rmf-server failed with error:
[start:rmf-server] npm ERR! Error: command failed
[start:rmf-server] npm ERR! in workspace: rmf-dashboard@0.0.1
[start:rmf-server] npm ERR! at location: /home/dch/rmf-web-main/packages/dashboard
[start:rmf-server] npm run start:rmf-server exited with code 1
[start:react] Compiled successfully!
[start:react]
[start:react] You can now view rmf-dashboard in the browser.
[start:react]
[start:react] Local: http://localhost:3000/
[start:react] On Your Network: http://10.10.17.90:3000/
[start:react]
[start:react] Note that the development build is not optimized.
[start:react] To create a production build, use npm run build.

**Comment by mayman99** [comment]
So the lifecycle error should appear when using the latest npm version, which it does in your case.
To confirm this, I've upgraded my npm version and I get a `lifecycle` error as well, and when I downgrade the npm version it goes away.

So I would suggest deleting the `node_module` in `rmf_web` root dir, downgrade npm to the LTS which should be `v16.14.2`, and bootstrap and run everything again.
Hopefully this will solve the problem for you, if not we can investigate further

**Comment by daichuihua** [comment]
> 
I install 16.14.2 by "nvm install 16.14.2" and "nvm use 16.14.2" ,then bootstrap and run everything again. it still don't works. as follow:
![Screenshot from 2022-04-12 16-40-30](https://user-images.githubusercontent.com/30583933/162919430-e652cab3-e6cd-466c-9329-49fe57be5424.png)

sometimes, when i run "./bootstrap" ,i found an ERROR : husky > Failed to install 
as follow:
![Screenshot from 2022-04-12 16-38-10](https://user-images.githubusercontent.com/30583933/162920110-63a4778c-d758-4a43-812a-388feec16685.png)

It 's matter or not?

**Comment by mayman99** [comment]
the error this time is coming from a ros2 package, it complains `numpy` is not installed

**Comment by daichuihua** [comment]
"cd rmf-web"&&"pipenv install numpy" and run"npm start" once again
bingo ,it works!
thank you very much ,mayman99

**Comment by mayman99** [comment]
Glad it worked!

**Comment by mayman99** [comment]
it was still not working on latest, we had to downgrade `npm` for it to work... issue persists

**Comment by aaronchongth** [comment]
Yup, apologies, I was following the conversation at the tail end of this thread and got a little trigger-happy. I'll be more careful next time

**Comment by aaronchongth** [comment]
I think https://github.com/open-rmf/rmf-web/pull/611 was to fix this issue, not https://github.com/open-rmf/rmf-web/pull/559. Will be closing this.
