### ISSUE TITLE
I get the door and lift shown on webpage but I can not get robot state

### ISSUE THREAD

**Issue by MRWANG995** [open-rmf/rmf-web#610]
### Required information:

- Operating system and version:
- Ubuntu 20.04
  - 
- OpenRMF installation type:
-  From source

- ROS distribution and version:
- galactic

  - 
- ROS installation type:
- from source

### Description of the bug

after I prepared everything, I run the cmd line 
` ros2 launch rmf_demos_ign office.launch.xml server_uri:="ws://localhost:3000"`
and there is a little trouble in the webpage

### Screenshots

![image](https://user-images.githubusercontent.com/98199152/168086725-0d95c39e-e898-4382-809f-c2780b0f6e25.png)
![image](https://user-images.githubusercontent.com/98199152/168087119-3dbc329e-60a7-4b12-9565-d2575c5fd0f5.png)
![image](https://user-images.githubusercontent.com/98199152/168086847-1d4e270c-acfe-41a5-a7f2-73927b2a188c.png)
![image](https://user-images.githubusercontent.com/98199152/168088619-36befe77-6cd1-47fc-af83-988f57773e31.png)

**Comment by aaronchongth** [comment]
Could you try running this?
```
ros2 launch rmf_demos_ign office.launch.xml server_uri:="ws://localhost:8001"
```

The default port that `api-server` uses is `8001` while `3000` is for the `dashboard`. The `dashboard` will fetch all the necessary data from the `api-server` once the server receives states from the fleet adapters.

This is mentioned [here](https://github.com/open-rmf/rmf_demos#rmf-web)
