### ISSUE TITLE
Good to have features in client-side dashboard

### ISSUE THREAD

**Issue by youliangtan** [open-rmf/rmf-web#629]
Per VC,
* Clicking on the robots in the tables, the maps do not center on that robot at the moment.
* New tasks created by current client do not show up on other dashboard clients readily, unless the refresh button is clicked.

These 2 notes should not block this PR from merging, new feature requests would be opened.

_Originally posted by @aaronchongth in https://github.com/open-rmf/rmf-web/issues/623#issuecomment-1181457594_

**Comment by koonpeng** [comment]
> Clicking on the robots in the tables, the maps do not center on that robot at the moment.
PR for this #630.

> New tasks created by current client do not show up on other dashboard clients readily, unless the refresh button is clicked.
This will require new endpoints in api-server, currently wip at branch `feat/active-tasks`.
