### ISSUE TITLE
Unable to switch floors

### ISSUE THREAD

**Issue by liugehaizaixue** [open-rmf/rmf-web#640]
There are three floors in the  hotel, but when I switch floors on the rmf-web, there is no response. After reading the source code carefully, I feel that the onbaselayerchange function is not triggered. 
At the same time, the size of icons such as elevators cannot be reduced further after being reduced to a certain extent. 
I wonder if there is any similar situation? Who can help me? Thank you

![QQ截图20220912132056](https://user-images.githubusercontent.com/103879998/189579200-087514f5-a193-4328-a8ec-9dc8e16f9d71.png)

![189519720-1b5e2cb2-c48f-48a1-b413-d932ac25a934](https://user-images.githubusercontent.com/103879998/189564789-203a5fbc-4b9f-42bf-8acc-eb77d9444e5e.png)

**Comment by liugehaizaixue** [comment]
![image](https://user-images.githubusercontent.com/103879998/189579431-b811635d-049c-4608-ac40-5e0d0a15bd74.png)

**Comment by aaronchongth** [comment]
Hello @liugehaizaixue! I'm sorry you're facing this problem, we have also noted this as an issue in the past https://github.com/open-rmf/rmf-web/issues/532, and will be putting together a fix soon. FYI @mayman99, just in case if you have a fix ready.
