### ISSUE TITLE
No package 'pangocairo' found 

### ISSUE THREAD

**Issue by ncnynl** [open-rmf/rmf-web#656]
### Required information:

- Operating system and version:
  - 
  - ubuntu 22.04
- OpenRMF installation type:
  - 
  - source install
- OpenRMF version or commit hash
  - 
- ROS distribution and version:
  - 
  - humble
- ROS installation type:
  - 
  - source
- Package or library, if applicable:
  - 
  - rmf-web

### Description of the bug

pnpm install will show No package 'pangocairo' found 

### Additional information

I have fixed it  
sudo apt install libpango1.0-dev

**Comment by aaronchongth** [comment]
Hello @ncnynl! I'm sorry to hear that you have some issues setting up rmf-web.

I just spun up a fresh `ubuntu:22.04` docker image, and managed to perform dependency installation `pnpm install` without issues. Here is the gist, https://gist.github.com/aaronchongth/81747479f53e15bed5333c0c0efc75c9.

`rmf-web` does not have any dependency on `pangocairo`, you may have run `pnpm install` in the wrong directory.

**Comment by ncnynl** [comment]
this is my successful install script for rmf_web base on humble https://gitee.com/ncnynl/commands/blob/master/commands_extra/ros2_rmf/shell/install_rmf_web_humble.sh @aaronchongth

**Comment by ncnynl** [comment]
I use nodejs 18.12.1 so  " pnpm env use --global 18"

**Comment by aaronchongth** [comment]
if the installation is failing due to not following the official installation instructions, it will not be considered a bug or issue.
