### ISSUE TITLE
When using web to cancel a task, api-server generates an error

### ISSUE THREAD

**Issue by liugehaizaixue** [open-rmf/rmf-web#680]
### Required information:

- Operating system and version:
  - Ubuntu 20.04
- OpenRMF installation type:
  - From source
- ROS distribution and version:
  - galactic

### Description of the bug

When I submit the 'cancel' task on the 'web' side, the 'api-server' sometimes produces the following error.
I don't know how this error is generated. Sometimes 'api-server 'can run normally, and sometimes this error occurs.

### Screenshots
![image](https://user-images.githubusercontent.com/103879998/220280726-a38eada8-add0-487e-8303-96dd511d539b.png)

**Comment by liugehaizaixue** [comment]
Tasks in api-server can be canceled successfully, but errors will be generated. After the above error is generated, 'code 500' will be generated when operating 'web' again
![image](https://user-images.githubusercontent.com/103879998/220286830-ccf5a8da-ff4d-4524-ab6c-2c205185c15d.png)

**Comment by liugehaizaixue** [comment]
I found another bug about 'cancel' on the web.
The task in `queue` status cannot be canceled. In fact, the task in rmf is canceled, but it still displays the queue status on the web interface.
![image](https://user-images.githubusercontent.com/103879998/221390821-9cf0af7a-e08d-4cfe-9009-4fb8cdccdb71.png)

![image](https://user-images.githubusercontent.com/103879998/221390807-ff2fbf40-ae75-4f03-a5f8-0cf56afc106f.png)

It seems that the task being executed can only be canceled normally on the web interface

**Comment by liugehaizaixue** [comment]
Rmf-web seems unable to verify the submitted task information.

For example, when I submit an empty task request, neither the dashboard nor the api-server verifies its information, so the task in the rmf is always in an unenforceable state.
![图片1](https://user-images.githubusercontent.com/103879998/221391023-69293ab2-0d2d-4c88-a9fa-2a5a5d9cb79b.png)
![图片2](https://user-images.githubusercontent.com/103879998/221391078-bfc563c7-069d-46b1-a79e-f53a6f5b3a44.png)

**Comment by aaronchongth** [comment]
> Rmf-web seems unable to verify the submitted task information.
For example, when I submit an empty task request, neither the dashboard nor the api-server verifies its information, so the task in the rmf is always in an unenforceable state.

thanks for bringing this up, we would appreciate it if you opened a separate ticket for this issue.

For cancellation errors it has been fixed via https://github.com/open-rmf/rmf-web/pull/682

For displaying `queue` after cancellation, just click refresh. We will be implementing auto-refresh soon that will not require a manual refresh.
