### ISSUE TITLE
Clicking on the robot icons does not zoom properly

### ISSUE THREAD

**Issue by Angatupyry** [open-rmf/rmf-web#712]
### Required information:
- Operating system and version: Ubuntu 22.04
- OpenRMF installation type: binary
- OpenRMF version or commit hash: 22.09
- ROS distribution and version: humble
- ROS installation type: binary
- Package or library, if applicable: rmf-web

### Description of the bug

Apparently zooming to the selected robot does not work with multilevel maps. 

### Steps to reproduce the bug

- Run rmf_web in dashboard package `pnpm run start`
- Launch RMF using `ros2 launch rmf_demos_gz hotel.launch.xml server_uri:="ws://localhost:8000/_internal"`

### Expected behavior

The map should zoom into the robot's position.
[office.webm](https://github.com/open-rmf/rmf-web/assets/37310205/6ceec333-147e-46f1-a4c5-959c20862a9c)

### Actual behavior

The map zooms in but in the wrong position.
[hotel.webm](https://github.com/open-rmf/rmf-web/assets/37310205/7fd688fd-4411-484a-8905-de50485838e8)

**Comment by aaronchongth** [comment]
Per VC, we should check the current behavior, since we are only centering and zooming onto robot icons when a robot row is selected.
