### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Steven-NYP** [open-rmf/rmf-web#725]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### OS and version

Ubuntu 22.04

### Open-RMF installation type

Source build

### Other Open-RMF installation methods

https://github.com/open-rmf/rmf#binary-installation

### Open-RMF version or commit hash

2.3.0

### ROS distribution

Rolling

### ROS installation type

Binaries

### Description of the bug

when executing the following in rmf-web:
![image](https://github.com/open-rmf/rmf-web/assets/37668174/bcb5221d-941e-44c2-8363-79109f1c6556)

The following error is displayed after entering pnpm start
![image](https://github.com/open-rmf/rmf-web/assets/37668174/cabdc23c-81b6-4974-8fc2-613336dba3e3)

### Steps to reproduce the bug

1. Follow the instructions in rmf-web optimized build section (https://github.com/open-rmf/rmf-web)
2. Execute pnpm start

### Additional information or screenshots

Seems like there is a missing directory

**Comment by aaronchongth** [comment]
Hello @Steven-NYP! Just a sanity check before we look further into this, did you perhaps run the `pnpm install` step at the root of the repository? This installs all the dependencies and sets up the python virtual environment which makes `.venv` available

**Comment by Steven-NYP** [comment]
Hi @aaronchongth, it's running well now. However I am getting the following error when I run "pnpm start" under Optimized Build

![image](https://github.com/open-rmf/rmf-web/assets/37668174/69915915-0962-4cb5-a634-b97696fc914e)

**Comment by xiangyang-95** [comment]
I am facing the same issue as well. What I have done to resolve was upgrade pip to newest version and downgrade crytography package to version 38.0.4 .
```
pip install --upgrade pip
pip install cryptography==38.0.4
```
