### ISSUE TITLE
Migrate react leaflet to react three fiber.

### ISSUE THREAD

**Issue by Angatupyry** [open-rmf/rmf-web#734]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

React Three Fiber offers a powerful alternative for rendering maps. 
By transitioning from React Leaflet to React Three Fiber, we gain the ability to build immersive environments with multi-level scaling. This means that we can seamlessly navigate and visualize objects at various levels of detail, providing a more natural and comprehensive understanding of geographical spaces. 

### Done

- Show robots.
- Show places as cube.
- Show places' names as text.
- Show RobotInformation when clicking a robot. 
- Show Trajectory. 

### In progress

- [x] Which object would represent the robot? For now, it is this [object](https://app.gazebosim.org/OpenRobotics/fuel/models/Hatchback) 
    - Aaron >> robots, we can stick to what we have in the past, have a default drawn circle if no logo or 3d asset is provided through dashboard resources
- [x] Draw an elevator (like a square) 
- [x] Show robots' names 
- [X] Show dispensers 
     - [X]  Which object would represent the dispensers? For now, it is a cube
     - A circular shape is shown according to the comment below.
- [X] Show ingestor 
     - [X]  Which object would represent the ingestor? For now, it is a cube
     - A circular shape is shown according to the comment below.
- [x] Fix the position of places when the level changes. Currently, the place names and cubes (represents places) look good on the first level but when switching to level 2 they are one floor down. 

- [x] Scale of waypoints and objects. 
- [ ] Calculate the scale correctly. 
     - Currently, the scale for both objects and places is a hardcoded Vector3 and, although they look good at all levels, it is not good practice. 
- [ ] Correctly calculate the z-value of the trajectory. 
    - Currently, it has a hardcoded value (4) 

### Fix (Details in videos)
- [x] Zoom. 
- [x] Automatic zoom when changing levels. 
    - The elevation is set to a standard value

[chrome-capture-2023-7-8.webm](https://github.com/open-rmf/rmf-web/assets/37310205/76f4b7cc-44fb-4f43-84eb-c9767edea328)
	
[chrome-capture-2023-7-8 (1).webm](https://github.com/open-rmf/rmf-web/assets/37310205/5507b205-a50a-49f9-b1b1-39e091698f3a)

**Comment by aaronchongth** [comment]
Per VC,
* Dispensers and ingestors in the legacy map is showed with icons like https://github.com/open-rmf/rmf_demos/blob/main/rmf_demos_dashboard_resources/office/main.json, we can start off with just circular waypoints if the waypoint is a dispenser or ingester, and have the same color as doors
* robots, we can stick to what we have in the past, have a default drawn circle if no logo or 3d asset is provided through dashboard resources

**Comment by aaronchongth** [comment]
Some notes, I can recreate the panning issue, using the mouse right-click.

**Comment by aaronchongth** [comment]
Regarding
```
Currently, the scale for both objects and places is a hardcoded Vector3 and, although they look good at all levels, it is not good practice
```

A stretch goal, to introduce a scale field beside icons in the dashboard resources, with meters/pixel, to accurately show robot icons to scale in maps.

**Comment by aaronchongth** [comment]
Leaving some behavioral change requirements here
- [ ] Elevator level indicator occluded
![image](https://github.com/open-rmf/rmf-web/assets/5383623/3de791b3-476f-409a-a834-c6f1c617b60e)
- [ ] Labels for elevator and door names
- [ ] Labels for doors open, moving or closed
- [ ] Zoom in and out buttons for maps
- [ ] Dropdown for selecting level or meshes/labels to display, otherwise it will look like 
![image](https://github.com/open-rmf/rmf-web/assets/5383623/d1cd507d-0e68-427a-b905-bde39de57a69)
- [ ] Changing tabs should retain same level, same view, same zoom level
- [ ] Map race condition, happens sometimes when first loading dashboard, or when changing levels

**Comment by aaronchongth** [comment]
Closing as we will be addressing the icon scale with support for image imports, using dashboard resources
