### ISSUE TITLE
[Bug]: The map and robot do not appear on the web application or when they do, they require lots of right/left clicks and zoom in

### ISSUE THREAD

**Issue by Tellext** [open-rmf/rmf-web#822]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### OS and version

Ubuntu 22.04

### Open-RMF installation type

Binaries

### Other Open-RMF installation methods

N/A

### Open-RMF version or commit hash

8.0.5

### ROS distribution

Humble

### ROS installation type

Binaries

### Other ROS installation methods

N/A

### Package or library, if applicable

 rmf-web

### Description of the bug

After launching rmf, free-fleet server on aws, connected to free-fleet client on the robot via husarnet cyclone dds, rmf-web, api-server and dashboard running on aws the robot and map appear very small in the dashboard even after multiple zoom ins, right clicks, also sometimes only the robot is shown and the map is not visible. This bug dosent allow the map to be seen clearly
Please check out the issue live by accessing [rmf.arani.io](http://rmf.arani.io/)

### Steps to reproduce the bug

**On aws**

1. Run rmf_web in dashboard package: pnpm start:react
2. Run rmf-web api-server package: pnpm start
3. launching rmf - ros2 launch rmf_demos rmf.launch.xml server_uri:="http://localhost:8000/_internal"
4. launching free fleet server - ros2 launch ff_examples_ros2 ff_server_tb3World.launch.xml

**On robot**

1. Nav2 stack ros foxy
2. launching free fleet client

### Expected behavior

N/A

### Actual behavior

N/A

### Additional information or screenshots

![rmf](https://github.com/open-rmf/rmf-web/assets/149538952/e0820e01-56a1-43b4-b599-5a52a8cc6777)

**Comment by aaronchongth** [comment]
Feature for configurable zoom levels in release `0.1.0`
