### ISSUE TITLE
[Other issue]: How to set a new task compose from web panel?

### ISSUE THREAD

**Issue by r-lucia** [open-rmf/rmf-web#879]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

I am trying to send a compose task to my fleet. I wanted to ask if this type of custom task can be sent via web panel. I tried using the "select file" option but in my case it doesn't work. How I can add this type of task to those supported by the panel?

**Comment by aaronchongth** [comment]
Closing as the `select file` option has been deprecated, users can use the `Custom compose task` task type to insert a full `compose` task request's description as a json, for example

```
{
  "category": "test",
  "phases": [
    {
      "activity": {
        "category": "sequence",
        "description": {
          "activities": [
            {
              "category": "go_to_place",
              "description": "pantry"
            }
          ]
        }
      }
    }
  ]
}
```
