### ISSUE TITLE
[Other issue]: Robots not appearing on UI, but showing on Gazebo & RViz

### ISSUE THREAD

**Issue by Bernard-Seng** [open-rmf/rmf-web#947]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

**Environment:** Ubuntu 22.04, ROS Humble

**RMF**: Source build from https://raw.githubusercontent.com/open-rmf/rmf/humble/rmf.repos
**RMF-web**: main branch

After running ros2 launch rmf_demos_gz office.launch.xml serveruri:="ws://localhost:8000/_internal", Gazebo and RViz loads normally. However, the web UI does not detect any robots. 

![Screenshot from 2024-05-23 16-01-07](https://github.com/open-rmf/rmf-web/assets/156041864/e36196f8-cb58-4dc5-b252-4168b9bf3c6e)

I tried to send tasks and the robots in both Gazebo and RViz moves accordingly and the web UI shows the path. 

![Screenshot from 2024-05-23 16-02-55](https://github.com/open-rmf/rmf-web/assets/156041864/923b6804-9dee-42e0-8d5c-7bcb83c38e87)

![Screenshot from 2024-05-23 16-03-14](https://github.com/open-rmf/rmf-web/assets/156041864/6e664036-78fc-4184-9925-183a8f96b723)

When clicking into the task overview, the task has been queued (because the UI has no robot to assign the task to)

![Screenshot from 2024-05-23 16-03-34](https://github.com/open-rmf/rmf-web/assets/156041864/08fd3c0d-43cc-438a-bb61-6fbfc75d9167)

The below is what I'm getting at the ros2 launch prompt 

![Screenshot from 2024-05-23 16-06-12](https://github.com/open-rmf/rmf-web/assets/156041864/f924dcc8-6dee-498a-b285-907d63ba53b7)

Any advice on this would be highly appreciated. Many thanks in advance!

**Comment by yuduo** [comment]
hi, do you solve the problem, i have same issure

**Comment by yuduo** [comment]
hi, do you solve the problem, i have same issure

**Comment by Bernard-Seng** [comment]
Not yet. Still facing this issue.

**Comment by aaronchongth** [comment]
Hi there, I've just tried on `main` and it seems to work fine for me,
![image](https://github.com/open-rmf/rmf-web/assets/5383623/0deebb64-7182-4109-877f-9361ee17b059)

Before we start looking into this more deeply, as a sanity check, have you guys tried refreshing your browser page?

**Comment by yuduo** [comment]
hi
i use ros2 topic echo robot_state ,can get the robot informations
but server_api http://localhost:8000/fleets
don't get the robot info

**Comment by Bernard-Seng** [comment]
From ros2 topic echo robot_state, I observed that the task_id for the robots keeps increasing even though no tasks were being assign to any of the robots.
