### ISSUE TITLE
[Bug]: pnpm install fails with Ubuntu 24.04

### ISSUE THREAD

**Issue by mxgrey** [open-rmf/rmf-web#952]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### OS and version

Ubuntu 22.04

### Open-RMF installation type

Source build

### Open-RMF version or commit hash

main

### ROS distribution

Rolling

### ROS installation type

Binaries

### Description of the bug

Using 24.04, when trying to install packages for rmf-web using `pnpm install` as instructed by the README, the installation fails [with this error message](https://gist.github.com/mxgrey/0cbb4035a84c57aec2e558ac5f268d38). The key part of the error appears to be
```
│ [pipenv.exceptions.InstallError]:       ValueError: invalid pyproject.toml config: `project`.
│ [pipenv.exceptions.InstallError]:       configuration error: `project` must contain ['name'] properties
│ [pipenv.exceptions.InstallError]:       [end of output]
```
This may be related to [this error report for asyncpg](https://github.com/MagicStack/asyncpg/issues/899) which is a dependency of rmf-web.

### Steps to reproduce the bug

Follow the README instructions while using Ubuntu 24.04.

Note that since pip in Python 3.12 no longer supports installing packages directly onto the system, I created a virtual environment to pip install the pipenv dependency. I don't know if this could be a factor in getting this error.

**Comment by koonpeng** [comment]
We no longer uses the system pipenv now, we now install pipenv inside the venv as part of the bootstrap script.
